### ISSUE TITLE
Kanye West breaks slide

### ISSUE THREAD

**Issue by Deadleg** [ccrama/Slide#1006]
[This post](https://www.reddit.com/r/cringepics/comments/460c44/kanye_west_breaking_down_on_twitter_begs_mark/) crashes slide when you view it in a submission list (frontpage and cringepics crash).

I get this error sometimes:
```
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception 'java.lang.IllegalStateException' thrown in void android.os.MessageQueue.nativePollOnce(long, int):-2
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]     in call to CallVoidMethodV
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]     from void android.os.MessageQueue.nativePollOnce(long, int)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x7535afe0 self=0xb4827800
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   | sysTid=16384 nice=0 cgrp=apps sched=0/0 handle=0xb6f37ec8
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=125 stm=18 core=0 HZ=100
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   | stack=0xbe3b9000-0xbe3bb000 stackSize=8MB
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #00 pc 000045b4  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #01 pc 00002e1d  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #02 pc 002524d5  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+84)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #03 pc 00235fb3  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+162)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #04 pc 000b0865  /system/lib/libart.so (art::JniAbort(char const*, char const*)+620)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #05 pc 000b0f95  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+68)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #06 pc 000b421d  /system/lib/libart.so (art::ScopedCheck::ScopedCheck(_JNIEnv*, int, char const*)+1324)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #07 pc 000bc5f3  /system/lib/libart.so (art::CheckJNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+42)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #08 pc 0005eb07  /system/lib/libandroid_runtime.so (???)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #09 pc 00072735  /system/lib/libandroid_runtime.so (android::NativeDisplayEventReceiver::dispatchVsync(long long, int, unsigned int)+40)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #10 pc 000728fd  /system/lib/libandroid_runtime.so (android::NativeDisplayEventReceiver::handleEvent(int, int, void*)+80)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #11 pc 000110a5  /system/lib/libutils.so (android::Looper::pollInner(int)+484)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #12 pc 0001114d  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #13 pc 0007dc59  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+22)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   native: #14 pc 000522cf  /data/dalvik-cache/arm/system@framework@boot.oat (Java_android_os_MessageQueue_nativePollOnce__JI+102)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   at android.os.MessageQueue.nativePollOnce(Native method)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   at android.os.MessageQueue.next(MessageQueue.java:143)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:122)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.main(ActivityThread.java:5272)
02-16 21:06:01.405 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke!(Native method)
02-16 21:06:01.406 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke(Method.java:372)
02-16 21:06:01.406 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
02-16 21:06:01.406 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
02-16 21:06:01.406 16384-16384/me.ccrama.redditslide A/art: art/runtime/check_jni.cc:65] 
```
and sometime I get this
```
02-16 21:08:02.655 17636-17636/me.ccrama.redditslide E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: me.ccrama.redditslide, PID: 17636
                                                                       java.lang.IllegalStateException: Unable to create layer for CardView
                                                                           at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                           at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                           at android.os.Looper.loop(Looper.java:122)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5272)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```

**Comment by l3d00m** [comment]
Cannot reproduce. It opens without problems for me. Maybe it's an inbuild Kanye West protection in your phone.

**Comment by ccrama** [comment]
Cannot get it to crash either. That first crash log looks like a device issue to me :(

**Comment by Deadleg** [comment]
Weird. More details if it happens again:

stock lg g3
Breaks in default layout, and with image in the middle of card and
uncropped.

**Comment by ccrama** [comment]
Darn. Try to report it if it happens again, I cannot find any g3 crash reports on my Google Play console

**Comment by Deadleg** [comment]
I was getting similar errors just opening slide a few days. Fix it by doing a fresh install.
