### ISSUE TITLE
All i did was unlock my phone...

### ISSUE THREAD

**Issue by xnaas** [ccrama/Slide#102]
## Info
ccrama pls
## Stacktrace
```java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)Caused by: net.dean.jraw.http.NetworkException: Request returned non-successful st
atus code: 401 Unauthorized
at net.dean.jraw.http.RestClient.execute(RestClient.java:132)
at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
at net.dean.jraw.pagin
ators.Pagin
ator.next(Pagin
ator.java:109)
at net.dean.jraw.pagin
ators.InboxPagin
ator.next(InboxPagin
ator.java:42)
at net.dean.jraw.pagin
ators.Pagin
ator.next(Pagin
ator.java:70)
at me.ccrama.redditslide.Notific
ations.CheckForMail$AsyncGetMail.doInBackground(CheckForMail.java:98)
at me.ccrama.redditslide.Notific
ations.CheckForMail$AsyncGetMail.doInBackground(CheckForMail.java:34)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)... 4 more```
Reported via Slide Crash Capture

**Comment by l3d00m** [comment]
I have the same crash.

**Comment by ccrama** [comment]
Means you are not authenticated and Reddit denied the request. Working on it!

**Comment by ccrama** [comment]
Merge with #306
