### ISSUE TITLE
Drawer doesn't slide out in an "opened" subreddit, and tapping the ℹ crashes 

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#105]
## Info
* Open subreddit using sidebar or presumably using a link, so that it's got the top left back button* Slide from right without results*Tap ℹ to crash

## Stacktrace
```java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.CheckBox.setHighlightColor(int)' on a null object reference
at me.ccrama.redditslide.Activities.SubredditView$4.onClick(SubredditView.java:228)
at android.view.View.performClick(View.java:4789)
at android.view.View$PerformClick.run(View.java:19881)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.disp
atchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5293)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Has been fixed with 824b092117ae42d3759f65f86ab984530f3d0965
