### ISSUE TITLE
Comment navigation arrows causes a crash if there are no more comments

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1053]
Slide version: 803788a5b4e4e1ffbb58a8973572de3aceb1625d
Android version: 5.1.1

```
E/AndroidRuntime( 4004): FATAL EXCEPTION: main
E/AndroidRuntime( 4004): Process: me.ccrama.redditslide, PID: 4004
E/AndroidRuntime( 4004): java.lang.IndexOutOfBoundsException: Invalid index 311, size is 311
E/AndroidRuntime( 4004):        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/AndroidRuntime( 4004):        at java.util.ArrayList.get(ArrayList.java:308)
E/AndroidRuntime( 4004):        at me.ccrama.redditslide.Adapters.CommentAdapter.getHiddenCountUpTo(CommentAdapter.java:1460)
E/AndroidRuntime( 4004):        at me.ccrama.redditslide.Adapters.CommentAdapter.getRealPosition(CommentAdapter.java:1446)
E/AndroidRuntime( 4004):        at me.ccrama.redditslide.Fragments.CommentPage.goDown(CommentPage.java:390)
E/AndroidRuntime( 4004):        at me.ccrama.redditslide.Fragments.CommentPage.access$400(CommentPage.java:51)
E/AndroidRuntime( 4004):        at me.ccrama.redditslide.Fragments.CommentPage$4.onClick(CommentPage.java:224)
E/AndroidRuntime( 4004):        at android.view.View.performClick(View.java:4780)
E/AndroidRuntime( 4004):        at android.view.View$PerformClick.run(View.java:19866)
E/AndroidRuntime( 4004):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 4004):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4004):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4004):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 4004):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4004):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4004):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 4004):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ccrama** [comment]
Fixed!
