### ISSUE TITLE
Youtube Link crashing

### ISSUE THREAD

**Issue by ashishbhandari** [ccrama/Slide#1110]
Slide version: Slide (Debug)  4.6.2-11-0184efb
Android version: 6.0.1 
Device Nexus 5

02-29 12:02:41.698 12046-12046/me.ccrama.redditslide.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: me.ccrama.redditslide.debug, PID: 12046
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide.debug/me.ccrama.redditslide.Activities.YouTubeView}: java.lang.IllegalArgumentException: Developer key cannot be null or empty
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              Caused by: java.lang.IllegalArgumentException: Developer key cannot be null or empty
                                                                                 at com.google.android.youtube.player.internal.ab.a(Unknown Source)
                                                                                 at com.google.android.youtube.player.YouTubePlayerView.initialize(Unknown Source)
                                                                                 at me.ccrama.redditslide.Activities.YouTubeView.onCreate(YouTubeView.java:51)
                                                                                 at android.app.Activity.performCreate(Activity.java:6251)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ashishbhandari** [comment]
For debug version **"secretconstants.properties" ** file is missing so method returning empty string. 

Debug version check is missing, exception could be handle defining something like apiKey = "UNDEFINED"

**Comment by ccrama** [comment]
Not applicable anymore, now it opens in the youtube app
