### ISSUE TITLE
slide kept crashing on Android Subreddit

### ISSUE THREAD

**Issue by gofirst2220** [ccrama/Slide#1118]
Slide version: 4.6.2
Android version: 5.1.1
Device: AT&T Samsung Galaxy S6

Like the title says, it kept crashing to home screen/ app drawer/ last open app, when I click on any of posts in Android subreddit to see the comments.

**Comment by Alexendoo** [comment]
Loading the comments of https://www.reddit.com/r/Android/comments/487tcv/console_os_creator_to_take_legal_action_against/

```
java.lang.IllegalStateException: Unable to create layer for CardView
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by Alexendoo** [comment]
Merge into #1119 (more information)
