### ISSUE TITLE
Crashes when opening comments view in some subreddits

### ISSUE THREAD

**Issue by SZE2** [ccrama/Slide#1119]
HTTPS://vid.me/7Ncg

Repeatable, log sent.

**Comment by SZE2** [comment]
Maybe it's the subreddits, I can't open posts in r/hfy. Sent log under name "crash on opening "HFY""
Post crashing is: Prey II 
https://www.reddit.com/r/HFY/comments/487zzy/prey_ii/

**Comment by SZE2** [comment]
Also, pressing "open externally on the that post in list view will open it in slide without crashing.

**Comment by Alexendoo** [comment]
What android/slide versions you on and device so we can take a look which crash report it is? Thanks

**Comment by Alexendoo** [comment]
Found it by the message:

```
java.lang.IllegalStateException: Unable to create layer for CardView
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Looks to be the same thing as #1118

**Comment by ccrama** [comment]
Erm that's a bug with android, not without Slide.

**Comment by ccrama** [comment]
*with

**Comment by Alexendoo** [comment]
Bisect shows d71061444f127cfb3559630dc2ac7a5abc9f4267 as the first bad commit

**Comment by ccrama** [comment]
Fixed with my last commit
