### ISSUE TITLE
Crash opening last post and swiping between posts 

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#1131]
Slide version: 4.6.2 dev build 
Android version: 5.1 

```
java.lang.IndexOutOfBoundsException: Invalid index 16, size is 16
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at me.ccrama.redditslide.Fragments.CommentPage.onCreateView(CommentPage.java:331)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:552)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
	at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:946)
	at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2910)
	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
	at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:276)
	at me.ccrama.redditslide.Activities.CommentsScreen$2.run(CommentsScreen.java:222)
	at android.app.Activity.runOnUiThread(Activity.java:5337)
	at me.ccrama.redditslide.Activities.CommentsScreen.updateSuccess(CommentsScreen.java:216)
	at me.ccrama.redditslide.Adapters.SubredditPosts$LoadData.onPostExecute(SubredditPosts.java:130)
	at me.ccrama.redditslide.Adapters.SubredditPosts$LoadData.onPostExecute(SubredditPosts.java:75)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:977)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
```

**Comment by ccrama** [comment]
Should now be fixed!
