### ISSUE TITLE
crash when opening reddit preferences in settings

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#1145]
Slide version: 4.6.2-92
Android version: 6.0.1

**Comment by Alexendoo** [comment]
```
E/AndroidRuntime( 3994): FATAL EXCEPTION: main
E/AndroidRuntime( 3994): Process: me.ccrama.redditslide.debug, PID: 3994
E/AndroidRuntime( 3994): java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide.debug/me.ccrama.redditslide.Activities.SettingsReddit}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
E/AndroidRuntime( 3994):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime( 3994):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime( 3994):        at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime( 3994):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime( 3994):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3994):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3994):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 3994):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3994):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3994):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 3994):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 3994): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
E/AndroidRuntime( 3994):        at me.ccrama.redditslide.Activities.SettingsReddit.onCreate(SettingsReddit.java:93)
E/AndroidRuntime( 3994):        at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 3994):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 3994):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime( 3994):        ... 10 more
```

**Comment by ccrama** [comment]
Fixed and pushed!
