### ISSUE TITLE
Slide crashes because of post in r/all

### ISSUE THREAD

**Issue by s1390** [ccrama/Slide#1185]
Slide version: 4.7.3
Android version: 6.0
View mode: Card with centered image
Picture mode: Big pic

It crashes after loading this post: https://www.reddit.com/r/oddlysatisfying/comments/49x5zw/modular_origami/

I assume it's because of the huge image.

**Comment by ccrama** [comment]
Not crashing for me, did you report it?

**Comment by Alexendoo** [comment]
```
E/AndroidRuntime( 7188): FATAL EXCEPTION: main
E/AndroidRuntime( 7188): Process: me.ccrama.redditslide, PID: 7188
E/AndroidRuntime( 7188): java.lang.ClassCastException: me.ccrama.redditslide.Activities.CommentsScreenSingle cannot be cast to me.ccrama.redditslide.Activities.CommentsScreen
E/AndroidRuntime( 7188):        at me.ccrama.redditslide.Fragments.CommentPage.onCreateView(CommentPage.java:313)
E/AndroidRuntime( 7188):        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
E/AndroidRuntime( 7188):        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
E/AndroidRuntime( 7188):        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
E/AndroidRuntime( 7188):        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
E/AndroidRuntime( 7188):        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
E/AndroidRuntime( 7188):        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
E/AndroidRuntime( 7188):        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:164)
E/AndroidRuntime( 7188):        at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
E/AndroidRuntime( 7188):        at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
E/AndroidRuntime( 7188):        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
E/AndroidRuntime( 7188):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 7188):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 7188):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime( 7188):        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
E/AndroidRuntime( 7188):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 7188):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 7188):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime( 7188):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime( 7188):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime( 7188):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 7188):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 7188):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime( 7188):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 7188):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 7188):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime( 7188):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime( 7188):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime( 7188):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 7188):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 7188):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime( 7188):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 7188):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime( 7188):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime( 7188):        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
E/AndroidRuntime( 7188):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime( 7188):        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
E/AndroidRuntime( 7188):        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
E/AndroidRuntime( 7188):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
E/AndroidRuntime( 7188):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime( 7188):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime( 7188):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime( 7188):        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime( 7188):        at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime( 7188):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime( 7188):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 7188):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 7188):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7188):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 7188):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7188):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7188):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 7188):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I managed to get this but it doesn't affect the git version

**Comment by Alexendoo** [comment]
No longer happens as of latest play store update either
