### ISSUE TITLE
Submitting a post causes a crash

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#124]
Submitting post appears to cause a crash (however the post still appears correctly)

```
E/AndroidRuntime( 9833): FATAL EXCEPTION: AsyncTask #3
E/AndroidRuntime( 9833): Process: me.ccrama.redditslide, PID: 9833
E/AndroidRuntime( 9833): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 9833):        at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 9833):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 9833):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 9833):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 9833):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 9833):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 9833):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 9833):        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 9833): Caused by: net.dean.jraw.http.NetworkException: Request returned non-successful status code: 400 Bad Request
E/AndroidRuntime( 9833):        at net.dean.jraw.http.RestClient.execute(RestClient.java:132)
E/AndroidRuntime( 9833):        at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
E/AndroidRuntime( 9833):        at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
E/AndroidRuntime( 9833):        at net.dean.jraw.RedditClient.getSubreddit(RedditClient.java:360)
E/AndroidRuntime( 9833):        at me.ccrama.redditslide.Activities.SubredditView$AsyncGetSubreddit.doInBackground(SubredditView.java:596)
E/AndroidRuntime( 9833):        at me.ccrama.redditslide.Activities.SubredditView$AsyncGetSubreddit.doInBackground(SubredditView.java:587)
E/AndroidRuntime( 9833):        at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 9833):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 9833):        ... 4 more
```

**Comment by ccrama** [comment]
So it submitted but still crashed? Strange...

**Comment by Alexendoo** [comment]
Yeah tested all three types (link, text, image) all made it through, but still crashed

**Comment by ccrama** [comment]
Done and done 484314627fd2e4f4a77e1f371bdb0a1cec739ff0
