### ISSUE TITLE
Repeated crashes after login 

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#1305]
Worked on install, but after input of user account details, crashes repeatedly on opening. 

Debug info:
 OS Version: 3.4.5-2351705(I9060XWUANB3)
 OS API Level: 17
 Device: baffinlite
 Model (and Product): GT-I9060 (baffinlitexx)
 RELEASE: 4.2.2
 BRAND: samsung
 DISPLAY: JDQ39.I9060XWUANB3
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: java_ss_baffinlite
 MANUFACTURER: samsung

Stacktrace: 

```java.lang.NullPointerException
	at me.ccrama.redditslide.Views.PopulateSubmissionViewHolder.getDomainName(PopulateSubmissionViewHolder.java:517)
	at me.ccrama.redditslide.Views.PopulateSubmissionViewHolder.PopulateSubmissionViewHolder(PopulateSubmissionViewHolder.java:383)
	at me.ccrama.redditslide.Adapters.SubmissionAdapter.onBindViewHolder(SubmissionAdapter.java)
	at me.ccrama.redditslide.Adapters.SubmissionAdapter.onBindViewHolder(SubmissionAdapter.java)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1683)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1467)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14905)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2213)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2027)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5164)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:561)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5319)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ccrama** [comment]
This person is on a version of Slide about 6 months old...
