### ISSUE TITLE
Tapped a link to another wiki page

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#131]
## Info
On /r/outoftheloop
## Stacktrace
```android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW d
at=reddit.com/r/OutOfTheLoop/wiki/index/retired_questions (has extras) }
at android.app.Instrument
ation.checkStartActivityResult(Instrument
ation.java:1781)
at android.app.Instrument
ation.execStartActivity(Instrument
ation.java:1501)
at android.app.Activity.startActivityForResult(Activity.java:3745)
at android.app.Activity.startActivity(Activity.java:4012)
at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:163)
at me.ccrama.redditslide.Views.MakeTextviewClickable$6.onClick(MakeTextviewClickable.java:567)
at me.ccrama.redditslide.ActiveTextView$1.onTouchEvent(ActiveTextView.java:103)
at android.widget.TextView.onTouchEvent(TextView.java:7985)
at android.view.View.disp
atchTouchEvent(View.java:8471)
at android.view.ViewGroup.disp
atchTransformedTouchEvent(ViewGroup.java:2405)
at android.view.ViewGroup.disp
atchTouchEvent(ViewGroup.java:2106)
at android.view.ViewGroup.disp
atchTransformedTouchEvent(ViewGroup.java:2405)
at android.view.ViewGroup.disp
atchTouchEvent(ViewGroup.java:2106)
at android.view.ViewGroup.disp
atchTransformedTouchEvent(ViewGroup.java:2405)
at android.view.ViewGroup.disp
atchTouchEvent(ViewGroup.java:2106)
at android.view.ViewGroup.disp
atchTransformedTouchEvent(ViewGroup.java:2405)
at android.view.ViewGroup.disp
atchTouchEvent(ViewGroup.java:2106)
at android.view.ViewGroup.disp
atchTransformedTouchEvent(ViewGroup.java:2405)
at android.view.ViewGroup.disp
atchTouchEvent(ViewGroup.java:2106)
at android.view.ViewGroup.disp
atchTransformedTouchEvent(ViewGroup.java:2405)
at android.view.ViewGroup.disp
atchTouchEvent(ViewGroup.java:2106)
at android.view.ViewGroup.disp
atchTransformedTouchEvent(ViewGroup.java:2405)
at android.view.ViewGroup.disp
atchTouchEvent(ViewGroup.java:2106)
at android.view.ViewGroup.disp
atchTransformedTouchEvent(ViewGroup.java:2405)
at android.view.ViewGroup.disp
atchTouchEvent(ViewGroup.java:2106)
at android.view.ViewGroup.disp
atchTransformedTouchEvent(ViewGroup.java:2405)
at android.view.ViewGroup.disp
atchTouchEvent(ViewGroup.java:2106)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDisp
atchTouchEvent(PhoneWindow.java:2369)
at com.android.internal.policy.impl.PhoneWindow.superDisp
atchTouchEvent(PhoneWindow.java:1719)
at android.app.Activity.disp
atchTouchEvent(Activity.java:2742)
at android.support.v7.internal.view.WindowCallbackWrapper.disp
atchTouchEvent(WindowCallbackWrapper.java:60)
at android.support.v7.internal.view.WindowCallbackWrapper.disp
atchTouchEvent(WindowCallbackWrapper.java:60)
at com.android.internal.policy.impl.PhoneWindow$DecorView.disp
atchTouchEvent(PhoneWindow.java:2330)
at android.view.View.disp
atchPointerEvent(View.java:8666)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
at android.view.InputEventReceiver.disp
atchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.n
ativePollOnce(N
ative Method)
at android.os.MessageQueue.next(MessageQueue.java:143)
at android.os.Looper.loop(Looper.java:122)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)```
Reported via Slide Crash Capture

**Comment by l3d00m** [comment]
Can reproduce it. Wikis linking to itself with a '#.....' at the end will crash slidr

**Comment by Alexendoo** [comment]
No longer seems to apply as anchors don't do anything anymore
