### ISSUE TITLE
Fast scrolling crashes slide (in 5.0.4 A3)

### ISSUE THREAD

**Issue by bantar** [ccrama/Slide#1323]
Slide version:  5.0.4 Alpha 3
Android version: 5.0 Galaxy S5

On certain subreddits, I sort by new and read from oldest to newest using Sort Order New.  This can have me scrolling 100's of messages to find my place.   With the many crashes previously, I was scrolling lots and as fast as I could to get to my starting point.  However, in all previous versions, scrolling was reliable.   

In A3, it crashes if I scroll too fast "after a page load".   If I see a page load and pause, then scroll fast again, it seems to be OK.   It will crash after the 1st page load, or 2nd or 3rd.    Does not depend on quantity, but rather on the user interaction speed after the load.    

Steps to recreate, Sort New in /r/all, then scroll down like a madman to message number 500.  (500 gives you a sense of urgency for scrolling lest you be there all day).   It should crash well before that.

**Comment by Alexendoo** [comment]
```
E/AndroidRuntime(26498): FATAL EXCEPTION: main
E/AndroidRuntime(26498): Process: me.ccrama.redditslide.debug, PID: 26498
E/AndroidRuntime(26498): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{92734a position=185 id=-1, oldPos=85, pLpos:85 scrap [attachedScrap] tmpDetached no parent}
E/AndroidRuntime(26498):        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4487)
E/AndroidRuntime(26498):        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4618)
E/AndroidRuntime(26498):        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4599)
E/AndroidRuntime(26498):        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
E/AndroidRuntime(26498):        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
E/AndroidRuntime(26498):        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
E/AndroidRuntime(26498):        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
E/AndroidRuntime(26498):        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2954)
E/AndroidRuntime(26498):        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2879)
E/AndroidRuntime(26498):        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3265)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(26498):        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(26498):        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime(26498):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime(26498):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(26498):        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime(26498):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime(26498):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(26498):        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(26498):        at android.view.View.layout(View.java:15671)
E/AndroidRuntime(26498):        at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(26498):        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
E/AndroidRuntime(26498):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
E/AndroidRuntime(26498):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(26498):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime(26498):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(26498):        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(26498):        at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(26498):        at android.view.Choreographer$FrameDi
```

**Comment by ccrama** [comment]
Should be fixed now
