### ISSUE TITLE
Entering a space into the go to subreddit field

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#133]
## Stacktrace
```java.lang.IndexOutOfBoundsException: setSpan (0 ... 1) ends beyond length 0
at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:351)
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:79)
at android.text.SpannableString.setSpan(SpannableString.java:46)
at android.text.TextUtils.copySpansFrom(TextUtils.java:1036)
at me.ccrama.redditslide.SubredditInputFilter.filter(SubredditInputFilter.java:29)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:464)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
at android.os.Handler.disp
atchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Cannot even type a space with Google keyboard. Seems like whatever keyboard you are using is ignoring filter cases. What keyboard are you using?

**Comment by Alexendoo** [comment]
I'm using Fleksy, so it's likely other keyboards also ignore that... interesting.

**Comment by ccrama** [comment]
Yeah i'd definitely report that to flesky, actually. I can't really fix this as it's a core OS crash because flesky is putting spaces somewhere it's impossible to have.

**Comment by Alexendoo** [comment]
Percent encode it and let reddit handle it in my opinion, it will return whether a sub exists or not

**Comment by Alexendoo** [comment]
Related: #143
