### ISSUE TITLE
Shadowbox browsing on a sub with a lot pictures crashes 5.1.0

### ISSUE THREAD

**Issue by realvz** [ccrama/Slide#1334]
Slide version:5.1.0
Android version:5.1.1 

Goto a sub with a lot of pictures. /r/gentlemanboners is a good example.  Scroll through pictures and Slide will crash. I tried it 10 times in multiple subs and it caused a crash consistently.  

This seems like a regression in 5.1.0, didn't have any issues in previous versions. 

I checked ram usage on the device and Slide was using 250mb which is normal and I had about 300mb of ram available. I also tried closing all apps and then browsing those subs and still encountered crash. 

Here's a link to the video 
https://vid.me/Q3Su

**Comment by Alexendoo** [comment]
```
E/AndroidRuntime(19305): FATAL EXCEPTION: AsyncTask #5
E/AndroidRuntime(19305): Process: me.ccrama.redditslide.debug, PID: 19305
E/AndroidRuntime(19305): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(19305):        at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(19305):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(19305):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(19305):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(19305):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(19305):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(19305):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(19305):        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(19305): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 14997484 byte allocation with 10379014 free bytes and 9MB until OOM
E/AndroidRuntime(19305):        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime(19305):        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E/AndroidRuntime(19305):        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
E/AndroidRuntime(19305):        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
E/AndroidRuntime(19305):        at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
E/AndroidRuntime(19305):        at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:61)
E/AndroidRuntime(19305):        at me.ccrama.redditslide.Views.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1659)
E/AndroidRuntime(19305):        at me.ccrama.redditslide.Views.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1634)
E/AndroidRuntime(19305):        at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(19305):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(19305):        ... 4 more
```

**Comment by Nxt3** [comment]
I can't seem to make this crash on my Pixel C or my Nexus 6P. Maybe it was fixed?

**Comment by Controless** [comment]
Can confirm, just happened to me now on the same subreddit.

**Comment by Nxt3** [comment]
What device are you using @realvz and @Alexendoo?

**Comment by realvz** [comment]
I'm using galaxy tab s2 8.0 running 5.1.1 and pixel c running Android N.

**Comment by rmenessec** [comment]
:+1: Nexus 10, Google stock 5.1.1 image (LMY49H); Nexus 6 Google stock 6.0.1 image (MMB29X)

**Comment by ccrama** [comment]
Fixed that second issue, first should be fixed too
