### ISSUE TITLE
Viewing a wiki

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#134]
## Info
In this case, attempting to view /r/archlinux's wiki
## Stacktrace
```java.lang.IllegalArgumentException: ViewPager does not have a PagerAdapter set
at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:611)
at me.ccrama.redditslide.Activities.Wiki$AsyncGetWiki.onPostExecute(Wiki.java:93)
at me.ccrama.redditslide.Activities.Wiki$AsyncGetWiki.onPostExecute(Wiki.java:65)
at android.os.AsyncTask.finish(AsyncTask.java:636)
at android.os.AsyncTask.access$500(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
at android.os.Handler.disp
atchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
I think this has been fixed for a while
