### ISSUE TITLE
Crash when swiping through comment threads near the end

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1366]
Slide version: 5.1.3
Android version: 5.1.1

Just doing the testing on the submissions from my frontpage, can reproduce

```
E/AndroidRuntime(18266): FATAL EXCEPTION: main
E/AndroidRuntime(18266): Process: me.ccrama.redditslide.debug, PID: 18266
E/AndroidRuntime(18266): java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 51, found: 101 Pager id: me.ccrama.redditslide.debug:id/content_view Pager class: class android.support.v4.view.ViewPager Problematic adapter: class me.ccrama.redditslide.Activities.CommentsScreen$OverviewPagerAdapter
E/AndroidRuntime(18266):        at android.support.v4.view.ViewPager.populate(ViewPager.java:1071)
E/AndroidRuntime(18266):        at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
E/AndroidRuntime(18266):        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
E/AndroidRuntime(18266):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime(18266):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime(18266):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime(18266):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime(18266):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime(18266):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime(18266):        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
E/AndroidRuntime(18266):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime(18266):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime(18266):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime(18266):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime(18266):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime(18266):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime(18266):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime(18266):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime(18266):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime(18266):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime(18266):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
E/AndroidRuntime(18266):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
E/AndroidRuntime(18266):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
E/AndroidRuntime(18266):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime(18266):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime(18266):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime(18266):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime(18266):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
E/AndroidRuntime(18266):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
E/AndroidRuntime(18266):        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
E/AndroidRuntime(18266):        at android.view.View.measure(View.java:17547)
E/AndroidRuntime(18266):        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
E/AndroidRuntime(18266):        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
E/AndroidRuntime(18266):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
E/AndroidRuntime(18266):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(18266):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime(18266):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(18266):        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(18266):        at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(18266):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(18266):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(18266):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(18266):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(18266):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(18266):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18266):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(18266):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(18266):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ccrama** [comment]
Fixed, thanks!
