### ISSUE TITLE
Crash when clicking on link in comment

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1374]
Slide version: 5.0.1-188

Happens when clicking on a comment with an image in it
Example: https://www.reddit.com/r/BlackPeopleTwitter/comments/4e6d0q/when_you_realize_white_girls_are_the_key_to/d1xgo9h

```
04-10 17:38:57.334 17244-17244/me.ccrama.redditslide.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: me.ccrama.redditslide.debug, PID: 17244
                                                                             java.lang.RuntimeException: Could not find activity from context:android.support.v7.widget.TintContextWrapper@d67e882
                                                                                 at me.ccrama.redditslide.SpoilerRobotoTextView.onLinkClick(SpoilerRobotoTextView.java:236)
                                                                                 at me.ccrama.redditslide.handler.TextViewLinkHandler.onTouchEvent(TextViewLinkHandler.java:101)
                                                                                 at android.widget.TextView.onTouchEvent(TextView.java:8325)
                                                                                 at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                 at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                 at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                                 at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                 at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
                                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                                                 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
                                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                                                 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                                                 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
                                                                                 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
                                                                                 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
                                                                             	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:60
```

**Comment by ccrama** [comment]
Caused by the new AppCompat library update :/

**Comment by ccrama** [comment]
Found a workaround
