### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by benjamindean** [ccrama/Slide#1427]
Slide version: 5.1.3
Android version: 6.0.1

Logcat:

```
I ActivityManager: Displayed me.ccrama.redditslide/.Activities.MainActivity: +367ms (total +573ms)
E RecyclerView: No adapter attached; skipping layout
E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
E AndroidRuntime: Process: me.ccrama.redditslide, PID: 11701
E AndroidRuntime: Theme: themes:{default=overlay:system, com.android.systemui=overlay:system}
E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E AndroidRuntime: 	at me.ccrama.redditslide.Adapters.SubredditPosts.loadPhotos(SubredditPosts.java:93)
E AndroidRuntime: 	at me.ccrama.redditslide.Adapters.SubredditPosts$LoadData.doInBackground(SubredditPosts.java:330)
E AndroidRuntime: 	at me.ccrama.redditslide.Adapters.SubredditPosts$LoadData.doInBackground(SubredditPosts.java:203)
E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E AndroidRuntime: 	... 4 more
W ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.MainActivity

```

**Comment by ccrama** [comment]
What sub are you opening?

**Comment by benjamindean** [comment]
@ccrama For some reason, everything is fine for the last hour or so. Probably, some post on **FrontPage** is the case. However, when app is finally opened correctly, I scrolled down as far as I could and everything loaded completely fine. 
`me.ccrama.redditslide.Adapters.SubredditPosts.loadPhotos(SubredditPosts.java:93)`
Maybe it has something to do with the domain of some submitted picture?

**Comment by ccrama** [comment]
Ah, should be fixed now. Thanks!
