### ISSUE TITLE
Shadowbox crash at 50th item

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#1438]
Slide version: 6adb4860530d47b9f05a61cd9f8c23fd5c204a53
Android version: 6.0.1

```
FATAL EXCEPTION: main
Process: me.ccrama.redditslide.debug, PID: 7788
Theme: themes:{}
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 50, found: 99 Pager id: me.ccrama.redditslide.debug:id/content_view Pager class: class android.support.v4.view.ViewPager Problematic adapter: class me.ccrama.redditslide.Activities.Shadowbox$OverviewPagerAdapter
    at android.support.v4.view.ViewPager.populate(ViewPager.java:1071)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
    at android.support.v4.view.ViewPager.smoothScrollTo(ViewPager.java:908)
    at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:623)
    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:609)
    at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2176)
    at android.view.View.dispatchTouchEvent(View.java:9301)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2659)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1787)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2620)
    at android.view.View.dispatchPointerEvent(View.java:9521)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQu
```

```
FATAL EXCEPTION: main
Process: me.ccrama.redditslide.debug, PID: 1183
Theme: themes:{}
java.lang.IndexOutOfBoundsException: Invalid index 50, size is 50
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.get(ArrayList.java:308)
    at me.ccrama.redditslide.Fragments.MediaFragment.onCreate(MediaFragment.java:175)
    at android.support.v4.app.Fragment.performCreate(Fragment.java:1951)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
    at android.support.v4.app.BackStackRecord.ensureFragmentsAreInitialized(BackStackRecord.java:1081)
    at android.support.v4.app.BackStackRecord.beginTransition(BackStackRecord.java:1036)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:662)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
    at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:164)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
    at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1019)
    at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2991)
    at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:279)
    at me.ccrama.redditslide.Activities.Shadowbox$2.run(Shadowbox.java:93)
    at android.app.Activity.runOnUiThread(Activity.java:5524)
    at me.ccrama.redditslide.Activities.Shadowbox.updateSuccess(Shadowbox.java:87)
    at me.ccrama.redditslide.Adapters.SubredditPosts$LoadData.onPostExecute(SubredditPosts.java:227)
    at me.ccrama.redditslide.Adapters.SubredditPosts$LoadData.onPostExecute(SubredditPosts.java:197)
    at android.os.AsyncTask.finish(AsyncTask.java:651)
    at android.os.AsyncTask.-wrap1(AsyncTask.java)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ccrama** [comment]
What commit are you on? I fixed this last night

**Comment by Alexendoo** [comment]
6adb4860530d47b9f05a61cd9f8c23fd5c204a53

**Comment by ccrama** [comment]
Fixed, thanks!
