### ISSUE TITLE
Links to non existent subreddits cause a crash

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#145]
Causes an issue when people use /r/subredditsashashtags for instance. The crash occurs after it appears to attempt loading the subreddit, rather than immediately clicking the link.
```
E/AndroidRuntime(10856): FATAL EXCEPTION: AsyncTask #3
E/AndroidRuntime(10856): Process: me.ccrama.redditslide, PID: 10856
E/AndroidRuntime(10856): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(10856):        at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(10856):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(10856):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(10856):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(10856):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(10856):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(10856):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(10856):        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(10856): Caused by: java.lang.IllegalArgumentException: Expected kind was not found. Expected 't5', got 'Listing'
E/AndroidRuntime(10856):        at net.dean.jraw.models.meta.ModelManager.validate(ModelManager.java:107)
E/AndroidRuntime(10856):        at net.dean.jraw.models.meta.ModelManager.parse(ModelManager.java:130)
E/AndroidRuntime(10856):        at net.dean.jraw.models.meta.ModelManager.create(ModelManager.java:23)
E/AndroidRuntime(10856):        at net.dean.jraw.http.RestResponse.as(RestResponse.java:96)
E/AndroidRuntime(10856):        at net.dean.jraw.RedditClient.getSubreddit(RedditClient.java:362)
E/AndroidRuntime(10856):        at me.ccrama.redditslide.Activities.SubredditView$AsyncGetSubreddit.doInBackground(SubredditView.java:596)
E/AndroidRuntime(10856):        at me.ccrama.redditslide.Activities.SubredditView$AsyncGetSubreddit.doInBackground(SubredditView.java:587)
E/AndroidRuntime(10856):        at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(10856):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(10856):        ... 4 more
```

**Comment by ccrama** [comment]
Fixed with 47557670bea5bd66e53f21273cac2acd9294f5a2
