### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Revel1020** [ccrama/Slide#147]
## Info
I have no idea. This is the second crash within the last 30 min. I have no idea what caused it. Both crashes occurred in different circumstances.
## Stacktrace
```java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)Caused by: java.lang.OutOfMemoryError: Failed to alloc
ate a 44386 byte alloc
ation with 37934 free bytes and 37KB until OOM
at java.lang.String.<init>(String.java:400)
at java.lang.String.copyValueOf(String.java:619)
at java.nio.CharArrayBuffer.toString(CharArrayBuffer.java:168)
at java.util.regex.M
atcher.reset(M
atcher.java:205)
at java.util.regex.M
atcher.reset(M
atcher.java:177)
at java.util.Scanner.resetM
atcher(Scanner.java:1676)
at java.util.Scanner.findDelimiterAfter(Scanner.java:2039)
at java.util.Scanner.setTokenRegion(Scanner.java:1953)
at java.util.Scanner.hasNext(Scanner.java:548)
at java.util.Scanner.hasNext(Scanner.java:526)
at net.dean.jraw.http.RestResponse.readContent(RestResponse.java:86)
at net.dean.jraw.http.RestResponse.<init>(RestResponse.java:52)
at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:71)
at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
at net.dean.jraw.RedditClient.getSubmission(RedditClient.java:344)
at me.ccrama.redditslide.Adapters.SubmissionComments$LoadD
ata.doInBackground(SubmissionComments.java:89)
at me.ccrama.redditslide.Adapters.SubmissionComments$LoadD
ata.doInBackground(SubmissionComments.java:61)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)... 4 more```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
You are out of memory. Could it be you are on a low ram device?

**Comment by Revel1020** [comment]
Impossible. I'm running CM12.1 on the HTC One M8. Which has 2GB of RAM. Also,  Slide is the 3rd or 4th app that is running. The other 3 are Google Search, Google+, and Whatsapp.

**Comment by Revel1020** [comment]
I have almost 1 GB of RAM free.

**Comment by ccrama** [comment]
Well the stacktrace says specifically 

     java.lang.OutOfMemoryError: Failed to alloc ate a 44386 byte alloc ation with 37934 free bytes and 37KB until OOM at java.lang.String.<init>

Could be your ROM is allocating memory inefficiently.

**Comment by Revel1020** [comment]
Not really. I was in the /r/microsoft subreddit which was filled with links.

**Comment by ccrama** [comment]
Interesting. Well try again with resents cleared and that might fix it.

**Comment by Revel1020** [comment]
Actually looking at my cached processes. Slide is using the most memory.

![](http://i.imgur.com/Nu3rmle.jpg)

**Comment by ccrama** [comment]
Yep. Most reddit apps use a lot of memory due to the image-heavy nature of the content. Can you do a side by side with Sync or another Reddit app for me please? I want to see what the difference is on your device

**Comment by Revel1020** [comment]
Here's are the 3. I cleared recents everytime and did the same actions on all 3 apps.
http://imgur.com/a/L4byi

**Comment by ccrama** [comment]
Huh mine seems to be using double than most. Will look into this!

**Comment by ccrama** [comment]
New image library lowers use by 30-50mb of RAM
