### ISSUE TITLE
Multitasking

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#150]
## Stacktrace
```java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'net.dean.jraw.http.HttpRequest$Builder net.dean.jraw.RedditClient.request()' on a null object reference
at net.dean.jraw.pagin
ators.Pagin
ator.next(Pagin
ator.java:99)
at net.dean.jraw.pagin
ators.SubredditPagin
ator.next(SubredditPagin
ator.java:53)
at net.dean.jraw.pagin
ators.Pagin
ator.next(Pagin
ator.java:70)
at me.ccrama.redditslide.Adapters.SubredditPosts$LoadD
ata.doInBackground(SubredditPosts.java:104)
at me.ccrama.redditslide.Adapters.SubredditPosts$LoadD
ata.doInBackground(SubredditPosts.java:63)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)... 4 more```
Reported via Slide Crash Capture

**Comment by l3d00m** [comment]
Dupe of #147?

**Comment by l3d00m** [comment]
Or #102
