### ISSUE TITLE
Debug crash on first launch

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#1527]
Slide version: 95c64f7
Android version: 6.0.1

```
04-23 14:08:43.657 31780-31780/me.ccrama.redditslide.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: me.ccrama.redditslide.debug, PID: 31780
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide.debug/me.ccrama.redditslide.Activities.MainActivity}: java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to me.ccrama.redditslide.SpoilerRobotoTextView
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                              Caused by: java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to me.ccrama.redditslide.SpoilerRobotoTextView
                                                                                 at me.ccrama.redditslide.Activities.MainActivity.onCreate(MainActivity.java:428)
                                                                                 at android.app.Activity.performCreate(Activity.java:6285)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by l3d00m** [comment]
Pretty sure it's an android studio issue. I have it from time to time too, but not only in Slide. Doing a clean build / rebuild should fix it!

**Comment by TheWorstNL** [comment]
Confirmed. Cleaning and rebuilding fixes it! Thanks!
