### ISSUE TITLE
Crash on filter subreddit from User > Submitted 

### ISSUE THREAD

**Issue by TheWorstNL** [ccrama/Slide#1529]
Slide version: 95c64f7
Android version: 6.0.1

Go to a user profile and then submitted tab. Filter a post based on subreddit.

```
FATAL EXCEPTION: main
                                                                             Process: me.ccrama.redditslide.debug, PID: 10502
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
                                                                                 at me.ccrama.redditslide.OfflineSubreddit.getSubreddit(OfflineSubreddit.java:147)
                                                                                 at me.ccrama.redditslide.OfflineSubreddit.getSubreddit(OfflineSubreddit.java:128)
```

**Comment by ccrama** [comment]
Fixed!
