### ISSUE TITLE
App crashes when clicking on "Edit your flair" for the subreddit /r/Agario

### ISSUE THREAD

**Issue by Controless** [ccrama/Slide#1568]
Slide version: 5.3.3-alpha
Android version: 6.0.1

**Comment by Alexendoo** [comment]
```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Collection.size()' on a null object reference
	at com.afollestad.materialdialogs.MaterialDialog$Builder.items(MaterialDialog.java:722)
	at me.ccrama.redditslide.Activities.MainActivity$13$1.onClick(MainActivity.java:809)
	at android.view.View.performClick(View.java)
	at android.view.View$PerformClick.run(View.java)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
```

**Comment by ccrama** [comment]
Fixed!
