### ISSUE TITLE
Disabled wikis cause a crash when attempting to view them

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#159]
For example, [/r/announcements](https://reddit.com/r/announcements)
```
E/AndroidRuntime( 8582): FATAL EXCEPTION: main
E/AndroidRuntime( 8582): Process: me.ccrama.redditslide, PID: 8582
E/AndroidRuntime( 8582): java.lang.IllegalArgumentException: ViewPager does not have a PagerAdapter set
E/AndroidRuntime( 8582): 	at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:611)
E/AndroidRuntime( 8582): 	at me.ccrama.redditslide.Activities.Wiki$AsyncGetWiki.onPostExecute(Wiki.java:93)
E/AndroidRuntime( 8582): 	at me.ccrama.redditslide.Activities.Wiki$AsyncGetWiki.onPostExecute(Wiki.java:65)
E/AndroidRuntime( 8582): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
E/AndroidRuntime( 8582): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
E/AndroidRuntime( 8582): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
E/AndroidRuntime( 8582): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8582): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 8582): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 8582): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8582): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8582): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 8582): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ccrama** [comment]
Fixed with 530ed7fbb1a47a21fac37055f4f0cd7f9476090d
