### ISSUE TITLE
Crash when unlocking phone

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#164]
## Stacktrace
```java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)Caused by: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='GET', url=https://oauth.reddit.com/r/all/hot, expectedMediaType=applic
ation/json, headers=User-Agent: android:me.ccrama.RedditSlide:v4.0 (by /u/ccrama)Authoriz
ation: bearer 32719971-uNgSSANoE2M1BFW8_GylJiaLfhoCache-Control: no-cache, body=null}
at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
at net.dean.jraw.pagin
ators.Pagin
ator.next(Pagin
ator.java:109)
at net.dean.jraw.pagin
ators.SubredditPagin
ator.next(SubredditPagin
ator.java:53)
at net.dean.jraw.pagin
ators.Pagin
ator.next(Pagin
ator.java:70)
at me.ccrama.redditslide.Adapters.SubredditPosts$LoadD
ata.doInBackground(SubredditPosts.java:102)
at me.ccrama.redditslide.Adapters.SubredditPosts$LoadD
ata.doInBackground(SubredditPosts.java:62)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)... 4 moreCaused by: java.net.UnknownHostException: Unable to resolve host "oauth.reddit.com": No address associ
ated with hostname
at java.net.InetAddress.lookupHostByName(InetAddress.java:435)
at java.net.InetAddress.getAllByNameImpl(InetAddress.java:255)
at java.net.InetAddress.getAllByName(InetAddress.java:218)
at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
at com.squareup.okhttp.internal.http.HttpEngine.cre
ateNextConnection(HttpEngine.java:344)
at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
at com.squareup.okhttp.Call.getResponse(Call.java:271)
at com.squareup.okhttp.Call$Applic
ationInterceptorChain.proceed(Call.java:228)
at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
at com.squareup.okhttp.Call.execute(Call.java:79)
at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
at net.dean.jraw.http.RestClient.execute(RestClient.java:120)... 13 more```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Merge with #306
