### ISSUE TITLE
Comments in Grid View (possiblt oom)

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#165]
## Stacktrace
```
java.lang.OutOfMemoryError: Failed to alloc
ate a 112908 byte alloc
ation with 14272 free bytes and 13KB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(N
ative Method)
at android.graphics.BitmapFactory.n
ativeDecodeAsset(N
ative Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:837)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:656)
at android.graphics.drawable.Drawable.cre
ateFromResourceStream(Drawable.java:1037)
at android.content.res.Resources.loadDrawableForCookie(Resources.java:3979)
at android.content.res.Resources.loadDrawable(Resources.java:3852)
at android.content.res.TypedArray.getDrawable(TypedArray.java:776)
at android.widget.ImageView.<init>(ImageView.java:151)
at android.widget.ImageButton.<init>(ImageButton.java:87)
at android.widget.ImageButton.<init>(ImageButton.java:83)
at android.support.v7.widget.AppComp
atImageButton.<init>(AppComp
atImageButton.java:60)
at android.support.v7.widget.AppComp
atImageButton.<init>(AppComp
atImageButton.java:56)
at android.support.v7.internal.app.AppComp
atViewInfl
ater.cre
ateView(AppComp
atViewInfl
ater.java:110)
at android.support.v7.app.AppComp
atDeleg
ateImplV7.cre
ateView(AppComp
atDeleg
ateImplV7.java:926)
at android.support.v7.app.AppComp
atDeleg
ateImplV7.onCre
ateView(AppComp
atDeleg
ateImplV7.java:980)
at android.support.v4.view.LayoutInfl
aterComp
atHC$FactoryWrapperHC.onCre
ateView(LayoutInfl
aterComp
atHC.java:44)
at android.view.LayoutInfl
ater.cre
ateViewFromTag(LayoutInfl
ater.java:732)
at android.view.LayoutInfl
ater.rInfl
ate(LayoutInfl
ater.java:813)
at android.view.LayoutInfl
ater.rInfl
ate(LayoutInfl
ater.java:821)
at android.view.LayoutInfl
ater.rInfl
ate(LayoutInfl
ater.java:821)
at android.view.LayoutInfl
ater.rInfl
ate(LayoutInfl
ater.java:821)
at android.view.LayoutInfl
ater.infl
ate(LayoutInfl
ater.java:511)
at android.view.LayoutInfl
ater.infl
ate(LayoutInfl
ater.java:415)
at me.ccrama.redditslide.Adapters.CommentAdapter.onCre
ateViewHolder(CommentAdapter.java:76)
at android.support.v7.widget.RecyclerView$Adapter.cre
ateViewHolder(RecyclerView.java:5223)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4449)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
at android.support.v7.widget.LinearLayoutManager$LayoutSt
ate.next(LinearLayoutManager.java:1961)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
at android.support.v7.widget.RecyclerView.disp
atchLayout(RecyclerView.java:2864)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:386)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:16942)
at android.view.ViewGroup.layout(ViewGroup.java:5409)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2457)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2160)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1300)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7017)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
at android.view.Choreographer.doCallbacks(Choreographer.java:590)
at android.view.Choreographer.doFrame(Choreographer.java:560)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.disp
atchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6891)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Can't reproduce.
