### ISSUE TITLE
Unchecked mail notification

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#172]
## Info
It's back baby, this one refuses to be killed
## Stacktrace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void me.ccrama.redditslide.Notific
ations.Notific
ationJobScheduler.cancel(android.content.Context)' on a null object reference
at me.ccrama.redditslide.Activities.Settings$4$2.onCheckedChanged(Settings.java:132)
at android.widget.CompoundButton.setChecked(CompoundButton.java:154)
at android.widget.CompoundButton.toggle(CompoundButton.java:113)
at android.widget.CompoundButton.performClick(CompoundButton.java:118)
at android.view.View$PerformClick.run(View.java:19866)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.disp
atchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Fixed c85abcb25dd12bc2566ee00e75c359de3c6602ac. Forgot to change it in  Inbox as well as Settings :s
