### ISSUE TITLE
Exception on start up. App not opening. 

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#1761]
Slide version: 5.3.7 update date today
Android version: 6

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: me.ccrama.redditslide, PID: 7715
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
                                                     at me.ccrama.redditslide.SubmissionViews.HeaderImageLinkView.doImageAndText(HeaderImageLinkView.java:110)
                                                     at me.ccrama.redditslide.SubmissionViews.HeaderImageLinkView.setSubmission(HeaderImageLinkView.java:88)
                                                     at me.ccrama.redditslide.SubmissionViews.PopulateSubmissionViewHolder.populateSubmissionViewHolder(PopulateSubmissionViewHolder.java:1549)
                                                     at me.ccrama.redditslide.Adapters.SubmissionAdapter.onBindViewHolder(SubmissionAdapter.java:279)
                                                     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5504)
                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4741)
                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                     at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
                                                     at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1538)
                                                     at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:657)
                                                     at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:592)
                                                     at me.ccrama.redditslide.Views.CatchStaggeredGridLayoutManager.onLayoutChildren(CatchStaggeredGridLayoutManager.java:24)
                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                                                     at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1482)
                                                     at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:147)
                                                     at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:294)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by ccrama** [comment]
Has already been fixed, update to the latest version

**Comment by prashantkhurana** [comment]
Awesome, thanks.
