### ISSUE TITLE
Exception on start up. App not opening.

### ISSUE THREAD

**Issue by prashantkhurana** [ccrama/Slide#1808]
Slide version: Debug Master
Android version:6

Getting exception while starting up in Android studio: 
`FATAL EXCEPTION: main
                                                                           Process: me.ccrama.redditslide.debug, PID: 7412
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide.debug/me.ccrama.redditslide.Activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setPopupTheme(int)' on a null object reference
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                            Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setPopupTheme(int)' on a null object reference
                                                                               at me.ccrama.redditslide.Activities.MainActivity.onCreate(MainActivity.java:456)
                                                                               at android.app.Activity.performCreate(Activity.java:6237)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
`

**Comment by ccrama** [comment]
Not seeing this issue anywhere, do you have anything custom running? That would only occur if the toolbar is missing from the layout, which it is not

**Comment by prashantkhurana** [comment]
Yeah, I am not sure too about it. I kept getting it, so I resolved it by reverting back to an old commit. I think we can close this issue. Must have had something to do with the emulator. If it occurs again, I'll let you know. Thanks !

**Comment by ccrama** [comment]
Sounds good, thank you!
