### ISSUE TITLE
Crash when opening profile

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#1937]
Slide version: 82bb3f77b45c32c1a4df0e5083e27e8747e7fe66

```
07-18 19:41:47.745 27869-27869/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: me.ccrama.redditslide, PID: 27869
                                                   java.lang.NumberFormatException: Invalid long: "null"
                                                       at java.lang.Long.invalidLong(Long.java:124)
                                                       at java.lang.Long.parseLong(Long.java:345)
                                                       at java.lang.Long.parseLong(Long.java:321)
                                                       at java.lang.Long.valueOf(Long.java:511)
                                                       at me.ccrama.redditslide.HasSeen.setHasSeenContrib(HasSeen.java:38)
                                                       at me.ccrama.redditslide.Adapters.ContributionPosts$LoadData.onPostExecute(ContributionPosts.java:74)
                                                       at me.ccrama.redditslide.Adapters.ContributionPosts$LoadData.onPostExecute(ContributionPosts.java:44)
                                                       at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                       at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

```
07-18 19:41:32.723 27869-27869/? W/FragmentManager: moveToState: Fragment state for ContributionsView{ffb9c32 #0 id=0x7f0f00da} not updated inline; expected state 3 found 2
07-18 19:41:41.872 27869-28167/? W/System.err: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='GET', url=https://oauth.reddit.com/prefs/friends?limit=100, expectedMediaType=application/json, headers=User-Agent: android:me.ccrama.RedditSlide:v5.3.9.3-140-82bb3f7
07-18 19:41:41.872 27869-28167/? W/System.err: Authorization: bearer StmTm3XtNvnQYkomASdX4BDYsv0
07-18 19:41:41.872 27869-28167/? W/System.err: Cache-Control: no-cache
07-18 19:41:41.873 27869-28167/? W/System.err: , body=null}
07-18 19:41:41.873 27869-28167/? W/System.err:     at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
07-18 19:41:41.873 27869-28167/? W/System.err:     at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
07-18 19:41:41.873 27869-28167/? W/System.err:     at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
07-18 19:41:41.873 27869-28167/? W/System.err:     at net.dean.jraw.paginators.Paginator.next(Paginator.java:114)
07-18 19:41:41.873 27869-28167/? W/System.err:     at net.dean.jraw.paginators.ImportantUserPaginator.next(ImportantUserPaginator.java:32)
07-18 19:41:41.873 27869-28167/? W/System.err:     at net.dean.jraw.paginators.Paginator.next(Paginator.java:70)
07-18 19:41:41.874 27869-28167/? W/System.err:     at me.ccrama.redditslide.UserSubscriptions.doFriendsOf(UserSubscriptions.java:353)
07-18 19:41:41.874 27869-28167/? W/System.err:     at me.ccrama.redditslide.UserSubscriptions.doFriendsOfMain(UserSubscriptions.java:341)
07-18 19:41:41.874 27869-28167/? W/System.err:     at me.ccrama.redditslide.Activities.MainActivity$AsyncNotificationBadge.doInBackground(MainActivity.java:3689)
07-18 19:41:41.874 27869-28167/? W/System.err:     at me.ccrama.redditslide.Activities.MainActivity$AsyncNotificationBadge.doInBackground(MainActivity.java:3647)
07-18 19:41:41.874 27869-28167/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-18 19:41:41.874 27869-28167/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-18 19:41:41.874 27869-28167/? W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
07-18 19:41:41.874 27869-28167/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-18 19:41:41.875 27869-28167/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-18 19:41:41.875 27869-28167/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-18 19:41:41.875 27869-28167/? W/System.err: Caused by: java.net.SocketTimeoutException: timeout
07-18 19:41:41.876 27869-28167/? W/System.err:     at okhttp3.internal.framed.FramedStream$StreamTimeout.newTimeoutException(FramedStream.java:600)
07-18 19:41:41.876 27869-28167/? W/System.err:     at okhttp3.internal.framed.FramedStream$StreamTimeout.exitAndThrowIfTimedOut(FramedStream.java:608)
07-18 19:41:41.876 27869-28167/? W/System.err:     at okhttp3.internal.framed.FramedStream.getResponseHeaders(FramedStream.java:142)
07-18 19:41:41.876 27869-28167/? W/System.err:     at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:146)
07-18 19:41:41.876 27869-28167/? W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
07-18 19:41:41.876 27869-28167/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-18 19:41:41.877 27869-28167/? W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
07-18 19:41:41.877 27869-28167/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-18 19:41:41.877 27869-28167/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-18 19:41:41.877 27869-28167/? W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
07-18 19:41:41.877 27869-28167/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-18 19:41:41.877 27869-28167/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-18 19:41:41.877 27869-28167/? W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
07-18 19:41:41.877 27869-28167/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-18 19:41:41.878 27869-28167/? W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
07-18 19:41:41.878 27869-28167/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-18 19:41:41.878 27869-28167/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-18 19:41:41.878 27869-28167/? W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
07-18 19:41:41.878 27869-28167/? W/System.err:     at okhttp3.RealCall.execute(RealCall.java:60)
07-18 19:41:41.878 27869-28167/? W/System.err:     at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:74)
07-18 19:41:41.878 27869-28167/? W/System.err:     at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
07-18 19:41:41.879 27869-28167/? W/System.err: 	... 15 more
```

**Comment by ccrama** [comment]
Has been fixed, thanks!
