### ISSUE TITLE
Crash when entering Moderation

### ISSUE THREAD

**Issue by Soberat** [ccrama/Slide#2051]
Slide version: https://github.com/ccrama/Slide/commit/dda6d3a5d69815fd21cdc818116d3ed91d48939f
Android version: 6.0.1

Stacktrace:
`me.ccrama.redditslide.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: me.ccrama.redditslide.debug, PID: 21837
                                                                             java.lang.ClassCastException: me.ccrama.redditslide.Activities.ModQueue cannot be cast to me.ccrama.redditslide.Activities.Inbox
                                                                                 at me.ccrama.redditslide.Adapters.InboxAdapter.onBindViewHolder(InboxAdapter.java:221)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5504)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4741)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                                 at me.ccrama.redditslide.Views.PreCachingLayoutManager.onLayoutChildren(PreCachingLayoutManager.java:25)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at me.ccrama.redditslide.SwipeLayout.SwipeBackLayout.onLayout(SwipeBackLayout.java:393)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2693)
                                                                                 at android.view.View.layout(View.java:16637)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                             	at android.view.ViewRootI`

**Comment by ccrama** [comment]
That would NOT have been good, thanks for the find!
