### ISSUE TITLE
Upvoted a post, received a crash!

### ISSUE THREAD

**Issue by russjr08** [ccrama/Slide#210]
## Stacktrace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference
at android.support.design.widget.Snackbar.<init>(Snackbar.java:180)
at android.support.design.widget.Snackbar.make(Snackbar.java:209)
at me.ccrama.redditslide.Vote$1.run(Vote.java:52)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.disp
atchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5294)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Where did you upvote this post?

**Comment by l3d00m** [comment]
it's also an older version he used

**Comment by ccrama** [comment]
Gonna close it then

**Comment by russjr08** [comment]
@l3d00m Sorry, the update wasn't out for me when the crash occurred. 

@ccrama This happened by upvoting a post while in the comments view (clicked the upvote arrow).

If it happens on the new update I'll re-report it. Thanks!
