### ISSUE TITLE
Build is broken?

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2105]
Slide version: 4870426742735d3231ba28586e9bf52aff068410
Android version: 6.0.1

Not sure what's going on, but ever since 9b640a82d7abd0ac61aa915bbcd8c4f073f24544 I've been unable to install Slide. Currently, (on 4870426742735d3231ba28586e9bf52aff068410), if I build a signed apk, I get an Android Studio error: `ExternalSystemException: String index out of range: -97`. The APK gets generated though, and I can install it; upon opening the app, it force closes and below is the log I captured from the crash.

Is it just me? I'm generating a signed apk of DevWithGPlayRelease.

```
08-31 23:31:19.729  1030  3068 I ActivityManager: Process me.ccrama.redditslide (pid 15949) has died
08-31 23:31:19.881  1030  1048 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
08-31 23:31:21.063  1030  3307 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=me.ccrama.redditslide/.Activities.SlideDefault bnds=[485,2178][956,2406] (has extras)} from uid 10100 on display 0
08-31 23:31:21.089  1030  4383 I ActivityManager: Start proc 16025:me.ccrama.redditslide/u0a228 for activity me.ccrama.redditslide/.Activities.SlideDefault
08-31 23:31:21.122 16025 16025 W System  : ClassLoader referenced unknown path: /data/app/me.ccrama.redditslide-2/lib/arm64
08-31 23:31:21.128 16025 16025 I MultiDex: VM with version 2.1.0 has multidex support
08-31 23:31:21.128 16025 16025 I MultiDex: install
08-31 23:31:21.128 16025 16025 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-31 23:31:21.177 16025 16025 D AndroidRuntime: Shutting down VM
08-31 23:31:21.180 16025 16025 E AndroidRuntime: FATAL EXCEPTION: main
08-31 23:31:21.180 16025 16025 E AndroidRuntime: Process: me.ccrama.redditslide, PID: 16025
08-31 23:31:21.180 16025 16025 E AndroidRuntime: java.lang.NoSuchFieldError
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:688)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:171)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at java.lang.Class.getAnnotation(Class.java:359)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at com.b.a.c.f.ag$a.<clinit>(SourceFile:170)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at com.b.a.c.f.ag$a.a(SourceFile:178)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at com.b.a.c.s.<clinit>(SourceFile:261)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at a.a.a.f.a.<clinit>(SourceFile:22)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at a.a.a.b.m.<init>(SourceFile:37)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at a.a.a.e.<init>(SourceFile:68)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at a.a.a.e.<init>(SourceFile:58)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at me.ccrama.redditslide.c.<init>(SourceFile:54)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at me.ccrama.redditslide.Reddit.onCreate(SourceFile:12674)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4712)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5422)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: Caused by: java.lang.NoSuchFieldException: No field PUBLIC_ONLY in class Lcom/b/a/a/e$a; (declaration of 'com.b.a.a.e$a' appears in /data/app/me.ccrama.redditslide-2/base.apk)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at java.lang.Class.getDeclaredField(Native Method)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:685)
08-31 23:31:21.180 16025 16025 E AndroidRuntime: 	... 24 more
08-31 23:31:21.181  1030  4373 W ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.SlideDefault
08-31 23:31:21.244  1030 14533 I OpenGLRenderer: Initialized EGL, version 1.4
08-31 23:31:21.699  1030  1043 W ActivityManager: Activity pause timeout for ActivityRecord{4c32a4e u0 me.ccrama.redditslide/.Activities.SlideDefault t8861 f}
08-31 23:31:22.271  4254  4574 W OpenGLRenderer: Incorrectly called buildLayer on View: fh, destroying layer...
08-31 23:31:22.271  4254  4574 W OpenGLRenderer: Incorrectly called buildLayer on View: fh, destroying layer...
```

**Comment by l3d00m** [comment]
Sounds like a Proguard issue to me after taking a quick look.

**Comment by freundTech** [comment]
Decoded stacktrace: (There is some Xposed stuff in there. You can just ignore that.)

    java.lang.NoSuchFieldError
        at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:688)
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
        at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:171)
        at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
        at java.lang.Class.getAnnotation(Class.java:359)
        at com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.<clinit>(VisibilityChecker.java:170)
        at com.fasterxml.jackson.databind.introspect.VisibilityChecker$Std.defaultInstance(VisibilityChecker.java:178)
        at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:261)
        at net.dean.jraw.util.JrawUtils.<clinit>(JrawUtils.java:22)
        at net.dean.jraw.http.RestClient.<init>(RestClient.java:37)
        at net.dean.jraw.RedditClient.<init>(RedditClient.java:68)
        at net.dean.jraw.RedditClient.<init>(RedditClient.java:58)
        at me.ccrama.redditslide.Authentication.<init>(Authentication.java:54)
        at me.ccrama.redditslide.Reddit.doMainStuff(Reddit.java:674)
        at me.ccrama.redditslide.Reddit.onCreate(Reddit.java:627)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4795)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
        at android.app.ActivityThread.access$1600(ActivityThread.java:157)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5525)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by freundTech** [comment]
Ref #2106

**Comment by ccrama** [comment]
Should be fixed now, I am also going to disable progaurd for the time being until we can work out any future issues in it. I'll make a new issue when I do so

**Comment by Nxt3** [comment]
@ccrama Why not keep it enabled for the next beta to do exactly what beta testing was made for? We can't possibly test everything.

**Comment by ccrama** [comment]
I'm going to enable it for the second alpha, probably not the first, though
