### ISSUE TITLE
Crash after returning from search

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2121]
Slide version: 7b074ac10166578151ecd33c776e4b3fa09f4e0e

Go to a sub you're not subscribed to or having in your sub list. Search that sub for something. Enter a post. Swipe back to the search results. Swipe back to the sub. Swipe back to overview. Crash. 

I'd diagnose it myself but I'm not at home now.

**Comment by ccrama** [comment]
I cannot reproduce this, maybe it's fixed?

**Comment by Nxt3** [comment]
I'll let you know soon. :P

**Comment by ccrama** [comment]
No worries, thank you!

**Comment by Nxt3** [comment]
```
09-06 22:18:40.138  9397  9397 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2001, result=-1, data=null} to activity {me.ccrama.redditslide/me.ccrama.redditslide.Activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5422)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at me.ccrama.redditslide.Activities.MainActivity.onActivityResult(MainActivity.java:230)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6456)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
09-06 22:18:40.138  9397  9397 E AndroidRuntime: 	... 9 more
```

Think it's the resetting of the sub search

**Comment by Nxt3** [comment]
I think I fixed this.
