### ISSUE TITLE
Graphical freakout if Imgur gif ends with .webm

### ISSUE THREAD

**Issue by Nxt3** [ccrama/Slide#2153]
Slide version: 5c8a51232447a3629409467e7beba30c52ec4966
Android version: 7.0

I stumbled upon an Imgur gif link that ended in `.webm`. Not sure how or why it had that extension, but it did.

See what I'm talking about here https://www.reddit.com/r/testslideforreddit/comments/52b4xz/test_freakout/

It is supposed to load this GIF: https://i.imgur.com/M4jCzLK.webm

This happens because the extension can be anything and Imgur fixes it automatically. If you click the above link, it will take you to https://i.imgur.com/M4jCzLK.gifv instead.

Edit: Not what I thought at first. Maybe more to it. Here is a log of the event.

```
09-11 18:54:29.324 32644-32644/me.ccrama.redditslide.debug I/VideoView: Destroyed surface number 0
09-11 18:54:29.461 32644-1272/me.ccrama.redditslide.debug E/(GifUtils.java:548): Error writing GIF: url = [https://i.imgur.com/M4jCzLK.webm], progressBar = [android.widget.ProgressBar{eea18fd V.ED..... ......ID 0,0-1440,48 #7f0f00e0 app:id/gifprogress}], c = [me.ccrama.redditslide.Activities.MediaView@896b33e], afterDone = [me.ccrama.redditslide.util.GifUtils$AsyncLoadGif@2bb659f]
09-11 18:54:29.462 32644-1272/me.ccrama.redditslide.debug E/(GifUtils.java:296): Error loading URL https://i.imgur.com/M4jCzLK.webm
                                                                                 java.io.FileNotFoundException: https://i.imgur.com/M4jCzLK.webm
                                                                                     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
                                                                                     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                                     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                                                                                     at me.ccrama.redditslide.util.GifUtils$AsyncLoadGif.writeGif(GifUtils.java:496)
                                                                                     at me.ccrama.redditslide.util.GifUtils$AsyncLoadGif.doInBackground(GifUtils.java:294)
                                                                                     at me.ccrama.redditslide.util.GifUtils$AsyncLoadGif.doInBackground(GifUtils.java:65)
                                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                     at java.lang.Thread.run(Thread.java:761)
```

**Comment by ccrama** [comment]
Seems like there is no data at .webm, and Imgur is redirecting you when you go to that page

**Comment by ccrama** [comment]
I think it's fixed now! Just had to replace .webm with .mp4 on Imgur links (also fixed the issue where it kept re-opening)

**Comment by Nxt3** [comment]
Thank you! :D
