### ISSUE TITLE
Crashes on Comment without Data

### ISSUE THREAD

**Issue by fangorntheent** [ccrama/Slide#229]
The app crashes after submitting a comment when data/wifi was disconnected while in-app.

**Comment by l3d00m** [comment]
## Stacktrace
```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'net.dean.jraw.http.HttpRequest$Builder net.dean.jraw.RedditClient.request()' on a null object reference
at net.dean.jraw.paginators.Paginator.next(Paginator.java:99)
at net.dean.jraw.paginators.SubredditPaginator.next(SubredditPaginator.java:53)
at net.dean.jraw.paginators.Paginator.next(Paginator.java:70)
at me.ccrama.redditslide.Adapters.SubredditPosts$LoadData.doInBackground(SubredditPosts.java:104)
at me.ccrama.redditslide.Adapters.SubredditPosts$LoadData.doInBackground(SubredditPosts.java:63)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)... 4 more
```
Slide v4.2.1, API v21
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Merge with #306
