### ISSUE TITLE
Writing into subreddit search crashes app if text field is not on screen

### ISSUE THREAD

**Issue by Mak-sime** [ccrama/Slide#2300]
I've found this bug that crashes the app randomly but here it is.

Let's say I wanna go to r/totallynotrobots because I am obviously not.

I go to the side menu, click the "Go to subreddit" textfield and enter a "t", then I scroll the first few results searching for my subreddit, but I see it is not there.
So I just add an "o" to the search terms and that's when it crashes.

Because I'm not sure I'm being clear, I shot a video on my phone to show it, here's the link of the GIF : https://gfycat.com/VelvetyNaturalFlamingo

Hope I was clear !

Slide version: 5.5.2-alpha3
Android version: 6.0.1

**Comment by Alexendoo** [comment]
Bisect shows it caused by cb5102e0ef2f1d00c764d52db7114b8c697574c6, but that seems to have been reverted between then and now, very odd

**Comment by ccrama** [comment]
When I begin to scroll, the keyboard disappears and I cannot type until it's back on the screen (the intended behavior). Wonder why that is not occurring on your device

**Comment by Mak-sime** [comment]
I use the Swiftkey Keyboard and thought maybe this was what allows me to have my keyboard even when scrolling but the crash is reproduced even with the default keyboard.

I am using a OnePlus 3 with the base OxygenOS but my Pixel C tablet running the same Slide version / Android version under RemixOS suffers the same crash

**Comment by Mak-sime** [comment]
I just did another test : 

I tried the same thing but with the physical keyboard on my Pixel C and it works just fine, I can keep typing, it still works fine.

Not sure if this helps though.

**Comment by touzainanboku** [comment]
Happens for me too. Z2, stock 6.0.1, Google Keyboard.

**Comment by touzainanboku** [comment]
I can reproduce it on my Z2 on Android 6.0.1. Using Slide 5.5.2 (stable), and Google Keyboard.

**Comment by pomkos** [comment]
I have this same issue using Swype keyboard, if I search for a subreddit and then scroll down while the keyboard is still up then Slide will crash.

**Comment by ccrama** [comment]
Can anyone provide me a stacktrace? I cannot reproduce this issue

**Comment by pomkos** [comment]
Sure, I could if you could give me a brief rundown on how to?




On Tue, Dec 20, 2016 at 2:25 AM -0500, "Carlos Crane" <notifications@github.com> wrote:












Can anyone provide me a stacktrace? I cannot reproduce this issue

**Comment by TheWorstNL** [comment]
`12-21 13:29:45.590 28407-28407/me.ccrama.redditslide E/RecyclerView: No adapter attached; skipping layout
12-21 13:29:48.102 28407-28407/me.ccrama.redditslide E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: me.ccrama.redditslide, PID: 28407
                                                                       java.lang.IllegalArgumentException: parameter must be a descendant of this view
                                                                           at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:5334)
                                                                           at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:5263)
                                                                           at android.view.ViewRootImpl.scrollToRectOrFocus(ViewRootImpl.java:2898)
                                                                           at android.view.ViewRootImpl.draw(ViewRootImpl.java:2506)
                                                                           at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2442)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2075)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6035)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5502)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-21 13:29:48.105 1122-4545/system_process W/ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.MainActivity
12-21 13:29:48.131 1122-1137/system_process E/ActivityManager: error name = Slide
12-21 13:29:48.131 1122-1137/system_process E/ActivityManager: error name = Slide
12-21 13:29:48.632 1122-1136/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{ebd2801 u0 me.ccrama.redditslide/.Activities.MainActivity t3600 f}`

**Comment by imurpops984** [comment]
Having this issue as well.  Also if I type any letter and scroll down the sub list then try to select one, it crashes.  Filtering by typing out the full sub name works fine; typing a letter, scrolling, then closing the keyboard before I make a selection works fine; but having a letter in the sub search bar causes crashes if I scroll and make a choice without closing the keyboard.

On version 5.5.4
LG G4: 6.0
Occurs with both default LG keyboard and Gboard
