### ISSUE TITLE
Crash when attempting to share image from lightbox

### ISSUE THREAD

**Issue by abraham** [ccrama/Slide#237]
## Info
Click on image from feed. Click on the share icon.
## Stacktrace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
at me.ccrama.redditslide.Activities.FullscreenImage.saveImageLocally(FullscreenImage.java:228)
at me.ccrama.redditslide.Activities.FullscreenImage.access$000(FullscreenImage.java:36)
at me.ccrama.redditslide.Activities.FullscreenImage$4$1.onLoadingComplete(FullscreenImage.java:109)
at com.nostra13.universalimageloader.core.DisplayBitmapTask.run(DisplayBitmapTask.java:72)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
Slide v4.2.1, API v23
Reported via Slide Crash Capture

**Comment by abraham** [comment]
Duplicate of #236
