### ISSUE TITLE
Multitask Crash

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#239]
Opened the App

Debug info:
 OS Version: 3.10.61-5556672(N920TUVU2COI5)
 OS API Level: 22
 Device: nobleltetmo
 Model (and Product): SM-N920T (nobleltetmo)
 RELEASE: 5.1.1
 BRAND: samsung
 DISPLAY: LMY47X.N920TUVU2COI5
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: samsungexynos7420
 MANUFACTURER: samsung

Stacktrace: 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.CreateMulti}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3149)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6891)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at me.ccrama.redditslide.Activities.CreateMulti.onCreate(CreateMulti.java:95)
	at android.app.Activity.performCreate(Activity.java:6550)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
	... 10 more
```

**Comment by Alexendoo** [comment]
App startup has changed a lot, this is likely no longer useful after many months
