### ISSUE TITLE
Pressing back on 😞 screen crashes

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#243]
Just crash the app by some other means, reopen, and press back.

Debug info:
 OS Version: 3.4.67-cyanogenmod-g06b8e73(5cfe9a0a92)
 OS API Level: 22
 Device: A0001
 Model (and Product): A0001 (bacon)
 RELEASE: 5.1.1
 BRAND: oneplus
 DISPLAY: bacon-userdebug 5.1.1 LMY48W 5cfe9a0a92 test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: bacon
 MANUFACTURER: OnePlus

Stacktrace: 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.Profile}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at me.ccrama.redditslide.Activities.Profile.onCreate(Profile.java:57)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
	... 10 more
```

**Comment by Alexendoo** [comment]
I have a feeling this is the same crash occurring twice rather than a different one, for instance with #244 I have a similar stack trace, when I hit back I do get another crash but the stack trace doesn't change from the previous one.

**Comment by ccrama** [comment]
Yeah can confirm that this is what's going on. Ill remove the back button function from that activity so that won't be possible!
