### ISSUE TITLE
Profile -> reorder pin-> + -> crash

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#245]
title

Debug info:
 OS Version: 3.1.10-g535135e(ea38de797e)
 OS API Level: 22
 Device: enrc2b
 Model (and Product): One X+ (enrc2b)
 RELEASE: 5.1.1
 BRAND: htc_europe
 DISPLAY: cm_enrc2b-userdebug 5.1.1 LMY48W ea38de797e test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: enrc2b
 MANUFACTURER: HTC

Stacktrace: 

```java.lang.NullPointerException: collection == null
	at java.util.ArrayList.<init>(ArrayList.java:94)
	at me.ccrama.redditslide.DragSort.ListViewDraggingAnimation.showSelectDialog(ListViewDraggingAnimation.java:142)
	at me.ccrama.redditslide.DragSort.ListViewDraggingAnimation$1.onClick(ListViewDraggingAnimation.java:64)
	at android.view.View.performClick(View.java:4789)
	at android.view.View$PerformClick.run(View.java:19881)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by ccrama** [comment]
Has been fixed in 4.2.2
