### ISSUE TITLE
Crashing upon reopening

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#252]
When you reopen Slide while it's still a cached process and not dismissed, it crashes for a fair majority of the time. 

Debug info:
 OS Version: 3.4.0-g2aa165e(2256973)
 OS API Level: 23
 Device: hammerhead
 Model (and Product): Nexus 5 (hammerhead)
 RELEASE: 6.0
 BRAND: google
 DISPLAY: MRA58K
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: hammerhead
 MANUFACTURER: LGE

Stacktrace: 

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='GET', url=https://oauth.reddit.com/r/slideforredditnotifs/hot, expectedMediaType=application/json, headers=User-Agent: android:me.ccrama.RedditSlide:v4.0 (by /u/ccrama)
Cache-Control: no-cache
, body=null}
	at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.paginators.Paginator.next(Paginator.java:109)
	at net.dean.jraw.paginators.SubredditPaginator.next(SubredditPaginator.java:53)
	at net.dean.jraw.paginators.Paginator.next(Paginator.java:70)
	at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:150)
	at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:27)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Caused by: java.net.UnknownHostException: Unable to resolve host "oauth.reddit.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
	at java.net.InetAddress.getAllByName(InetAddress.java:215)
	at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
	at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
	at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
	at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
	... 13 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Posix.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
	... 29 more
```

**Comment by ccrama** [comment]
Merge into #306
