### ISSUE TITLE
App crashed when Settings Backup touched

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#257]
The app crashed when I tried to use the new settings backup

Debug info:
 OS Version: 3.4.0-SkyDragon-v5.0.2-g616e817-dirty(1525410464a1b)
 OS API Level: 22
 Device: g3
 Model (and Product): VS985 4G (g3_vzw)
 RELEASE: 5.1.1
 BRAND: lge
 DISPLAY: SkyDragon V6 - LMY47V
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: g3
 MANUFACTURER: LGE

Stacktrace: 

```java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.SettingsBackup}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2378)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2440)
	at android.app.ActivityThread.access$800(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5422)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' on a null object reference
	at me.ccrama.redditslide.Activities.SettingsBackup.onStart(SettingsBackup.java:68)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
	at android.app.Activity.performStart(Activity.java:6072)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2341)
	... 11 more
```

**Comment by ccrama** [comment]
Do you have pro by chance?

**Comment by ccrama** [comment]
Fixed. you need pro
