### ISSUE TITLE
Backup crash

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#259]
tried to backup and app crashed instantly

Debug info:
 OS Version: 3.10.20-x86_64_moor(WW_epad-12.14.1.19-20150828)
 OS API Level: 21
 Device: K007
 Model (and Product): K007 (WW_K007)
 RELEASE: 5.0.1
 BRAND: asus
 DISPLAY: LRX22C.WW_epad-12.14.1.19-20150828
 CPU_ABI: x86
 CPU_ABI2: armeabi-v7a
 HARDWARE: mofd_v1
 MANUFACTURER: asus

Stacktrace: 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.SettingsBackup}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
	at android.app.ActivityThread.access$800(ActivityThread.java:147)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5264)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' on a null object reference
	at me.ccrama.redditslide.Activities.SettingsBackup.onStart(SettingsBackup.java:68)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
	at android.app.Activity.performStart(Activity.java:5991)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
	... 10 more
```

**Comment by ccrama** [comment]
Fixed. You need Slide Pro to do backups
