### ISSUE TITLE
Crash on backup

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#261]
App crashes when tryng to backup (Just after tapping) 

Debug info:
 OS Version: 3.4.0-ElementalX-N5-4.08(1863243)
 OS API Level: 22
 Device: hammerhead
 Model (and Product): Nexus 5 (hammerhead)
 RELEASE: 5.1.1
 BRAND: google
 DISPLAY: LMY48B
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: hammerhead
 MANUFACTURER: LGE

Stacktrace: 

```java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.SettingsBackup}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' on a null object reference
	at me.ccrama.redditslide.Activities.SettingsBackup.onStart(SettingsBackup.java:68)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
	at android.app.Activity.performStart(Activity.java:6006)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
	... 11 more
```

**Comment by Alexendoo** [comment]
Very similar to #259
