### ISSUE TITLE
When pressing backup

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#262]
Crashes

Debug info:
 OS Version: 3.4.0-g17207298(509530.6)
 OS API Level: 21
 Device: htc_m8
 Model (and Product): HTC One_M8 (h3g_uk)
 RELEASE: 5.0.2
 BRAND: htc
 DISPLAY: LRX22G release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: HTC

Stacktrace: 

```java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.SettingsBackup}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5696)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' on a null object reference
	at me.ccrama.redditslide.Activities.SettingsBackup.onStart(SettingsBackup.java:68)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1288)
	at android.app.Activity.performStart(Activity.java:5974)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2374)
	... 10 more
```

**Comment by Alexendoo** [comment]
Pretty much the same as #259
