### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#264]
I was opening a Reddit link from the sidebar when it crashed

Debug info:
 OS Version: 3.4.0-4584173(I545VRUGOC1)
 OS API Level: 21
 Device: jfltevzw
 Model (and Product): SCH-I545 (jfltevzw)
 RELEASE: 5.0.1
 BRAND: Verizon
 DISPLAY: LRX22C.I545VRUGOC1
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: samsung

Stacktrace: 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at me.ccrama.redditslide.Adapters.CommentAdapter.reset(CommentAdapter.java:130)
	at me.ccrama.redditslide.Fragments.CommentPage.doData(CommentPage.java:259)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.onPostExecute(SubmissionComments.java:74)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.onPostExecute(SubmissionComments.java:60)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by ccrama** [comment]
Not helpful, can't reproduce without more info.
