### ISSUE TITLE
Adding /r/all to a multireddit causes a crash

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#265]
It should not be possible to add /r/all to a multireddit (however /r/frontpage **is** okay).

![](http://puu.sh/kWYIP.png)

```
E/AndroidRuntime( 2794): FATAL EXCEPTION: AsyncTask #5
E/AndroidRuntime( 2794): Process: me.ccrama.redditslide, PID: 2794
E/AndroidRuntime( 2794): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 2794):        at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 2794):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 2794):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 2794):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 2794):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 2794):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 2794):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 2794):        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 2794): Caused by: net.dean.jraw.http.NetworkException: Request returned non-successful status code: 400 Bad Request
E/AndroidRuntime( 2794):        at net.dean.jraw.http.RestClient.execute(RestClient.java:132)
E/AndroidRuntime( 2794):        at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
E/AndroidRuntime( 2794):        at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
E/AndroidRuntime( 2794):        at net.dean.jraw.managers.MultiRedditManager.createOrUpdate(MultiRedditManager.java:73)
E/AndroidRuntime( 2794):        at me.ccrama.redditslide.Activities.CreateMulti$SaveMulti.doInBackground(CreateMulti.java:150)
E/AndroidRuntime( 2794):        at me.ccrama.redditslide.Activities.CreateMulti$SaveMulti.doInBackground(CreateMulti.java:145)
E/AndroidRuntime( 2794):        at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 2794):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 2794):        ... 4 more
```

**Comment by ccrama** [comment]
Oops.

**Comment by ccrama** [comment]
Now it doesn't show up :D
