### ISSUE TITLE
mutlireddit names are not sanitized

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#266]
```
E/AndroidRuntime( 7483): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime( 7483): Process: me.ccrama.redditslide, PID: 7483
E/AndroidRuntime( 7483): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 7483):        at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 7483):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 7483):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 7483):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 7483):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 7483):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 7483):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 7483):        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 7483): Caused by: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='PUT', url=https://oauth.reddit.com/api/multi/user/alexendoo/m/Crash Time, expectedMediaType=application/json, headers=User-Agent: android:me.ccrama.RedditSlide:v4.0 (by /u/ccrama)
E/AndroidRuntime( 7483): Authorization: bearer ~~~~~Snip~~~~~~
E/AndroidRuntime( 7483): , body=net.dean.jraw.http.RequestBody$DefaultRequestBody@39280beb}
E/AndroidRuntime( 7483):        at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
E/AndroidRuntime( 7483):        at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
E/AndroidRuntime( 7483):        at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
E/AndroidRuntime( 7483):        at net.dean.jraw.managers.MultiRedditManager.createOrUpdate(MultiRedditManager.java:73)
E/AndroidRuntime( 7483):        at me.ccrama.redditslide.Activities.CreateMulti$SaveMulti.doInBackground(CreateMulti.java:150)
E/AndroidRuntime( 7483):        at me.ccrama.redditslide.Activities.CreateMulti$SaveMulti.doInBackground(CreateMulti.java:145)
E/AndroidRuntime( 7483):        at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 7483):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 7483):        ... 4 more
E/AndroidRuntime( 7483): Caused by: java.io.IOException: Illegal character in path at index 57: https://oauth.reddit.com/api/multi/user/alexendoo/m/Crash Time
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Request.uri(Request.java:66)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:643)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:218)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Call.getResponse(Call.java:271)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
E/AndroidRuntime( 7483):        at com.squareup.okhttp.Call.execute(Call.java:79)
E/AndroidRuntime( 7483):        at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
E/AndroidRuntime( 7483):        at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
E/AndroidRuntime( 7483):        ... 11 more
```

**Comment by Alexendoo** [comment]
Going to merge with #143
