### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#268]
After backing up the dialog started to flash nonstop before crashing

Debug info:
 OS Version: 3.4.0-4584173(I545VRUGOC1)
 OS API Level: 21
 Device: jfltevzw
 Model (and Product): SCH-I545 (jfltevzw)
 RELEASE: 5.0.1
 BRAND: Verizon
 DISPLAY: LRX22C.I545VRUGOC1
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: samsung

Stacktrace: 

```
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
	at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1315)
	at com.afollestad.materialdialogs.AlertDialogWrapper$Builder.show(AlertDialogWrapper.java:174)
	at me.ccrama.redditslide.Activities.SettingsBackup$5.onResult(SettingsBackup.java:236)
	at me.ccrama.redditslide.Activities.SettingsBackup$5.onResult(SettingsBackup.java:221)
	at com.google.android.gms.internal.zzlc$zza.zzb(Unknown Source)
	at com.google.android.gms.internal.zzlc$zza.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by Alexendoo** [comment]
Related but not the same: #259

**Comment by ccrama** [comment]
Somehow the activity finished before the dialog was shown.

**Comment by ccrama** [comment]
Can't reproduce
