### ISSUE TITLE
Changing the comment sorting crashes slide

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#270]
while browsing sub Reddit, changing the comments order from top to new crashes app.

Debug info:
 OS Version: 3.4.0-g5093fc3(452965.9)
 OS API Level: 21
 Device: htc_m8wl
 Model (and Product): HTC6525LVW (HTCOneM8vzw)
 RELEASE: 5.0.1
 BRAND: htc
 DISPLAY: LRX22C release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: HTC

Stacktrace: 

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1682c2f4 position=90 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent}
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4247)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4378)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:386)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15684)
	at android.view.ViewGroup.layout(ViewGroup.java:4981)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2186)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1920)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1106)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6018)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
	at android.view.Choreographer.doCallbacks(Choreographer.java:596)
	at android.view.Choreographer.doFrame(Choreographer.java:557)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5696)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by ccrama** [comment]
Fixed in last commit
