### ISSUE TITLE
IndexOutOfBoundsException when opening slide for reddit.

### ISSUE THREAD

**Issue by jonathanostinowsky** [ccrama/Slide#2706]
Slide version: 5.8.2
Android version: 8.1.0 April OTA

```
04-02 14:30:28.924 14237 14237 D AndroidRuntime: Shutting down VM
04-02 14:30:28.924 14237 14237 E AndroidRuntime: FATAL EXCEPTION: main
04-02 14:30:28.924 14237 14237 E AndroidRuntime: Process: me.ccrama.redditslide, PID: 14237
04-02 14:30:28.924 14237 14237 E AndroidRuntime: java.lang.RuntimeException: Unable to create application me.ccrama.redditslide.Reddit: java.lang.IndexOutOfBoundsException
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:106)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:164)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6494)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-02 14:30:28.924 14237 14237 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.content.res.StringBlock.nativeGetString(Native Method)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.content.res.StringBlock.get(StringBlock.java:82)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.content.res.AssetManager.getResourceValue(AssetManager.java:236)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.content.res.AssetManager.getResourceText(AssetManager.java:164)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.content.res.Resources.getText(Resources.java:335)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.content.res.Resources.getString(Resources.java:433)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.content.Context.getString(Context.java:556)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at me.ccrama.redditslide.util.AdBlocker.init(AdBlocker.java:22)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at me.ccrama.redditslide.Reddit.doMainStuff(Reddit.java:697)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at me.ccrama.redditslide.Reddit.onCreate(Reddit.java:642)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
04-02 14:30:28.924 14237 14237 E AndroidRuntime:     ... 8 more
04-02 14:30:28.929   946  2783 W ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.Slide
04-02 14:30:28.934   946   976 I ActivityManager: Showing crash dialog for package me.ccrama.redditslide u0
```

**Comment by PiwwowPants** [comment]
This definitely looks like the AdBlocker crash that was fixed (I hope) in this commit
 https://github.com/ccrama/Slide/blob/28aa41a9f85109a3ec55e4ec52ec80fc3f8a2199/app/src/main/java/me/ccrama/redditslide/util/AdBlocker.java

It's in the alpha release right now I believe.

**Comment by ccrama** [comment]
@PiwwowPants 's changes fixed this
