### ISSUE TITLE
Sliding right through r/all posts

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#271]
Title 

Debug info:
 OS Version: 3.4.0-g17207298(509530.6)
 OS API Level: 21
 Device: htc_m8
 Model (and Product): HTC One_M8 (h3g_uk)
 RELEASE: 5.0.2
 BRAND: htc
 DISPLAY: LRX22G release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: HTC

Stacktrace: 

```java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 8204 byte allocation with 2652 free bytes and 2652B until OOM
	at java.util.Scanner.expandBuffer(Scanner.java:2096)
	at java.util.Scanner.readMore(Scanner.java:2060)
	at java.util.Scanner.findDelimiterAfter(Scanner.java:2038)
	at java.util.Scanner.setTokenRegion(Scanner.java:1953)
	at java.util.Scanner.hasNext(Scanner.java:548)
	at java.util.Scanner.hasNext(Scanner.java:526)
	at net.dean.jraw.http.RestResponse.readContent(RestResponse.java:86)
	at net.dean.jraw.http.RestResponse.<init>(RestResponse.java:52)
	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:71)
	at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.RedditClient.getSubmission(RedditClient.java:344)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.doInBackground(SubmissionComments.java:88)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.doInBackground(SubmissionComments.java:60)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by l3d00m** [comment]
According to stackoverflow this happens because 1. simply not enough memory or 2. because memory leaks.

**Comment by ccrama** [comment]
Out of memory. Can only be fixed with future optimizations. I have LeakCanary installed so it's unlikely a mem leak (or I would have fixed it by now)
