### ISSUE TITLE
Crash when opening specific subreddit

### ISSUE THREAD

**Issue by sharedkestrel** [ccrama/Slide#2835]
With version 5.9-alpha1, opening the r/overlord subreddit causes a crash.

Log:

```
08-10 09:29:26.698 29090 29090 W System.err: 	at me.ccrama.redditslide.ContentType.getContentType(ContentType.java:155)

08-10 09:29:26.698 29090 29090 W System.err: 	at me.ccrama.redditslide.Activities.MainActivity.checkClipboard(MainActivity.java:1317)

08-10 09:29:26.698 29090 29090 W System.err: 	at me.ccrama.redditslide.Activities.MainActivity.onResume(MainActivity.java:1349)

08-10 09:29:26.781 29090 29134 I me.ccrama.redditslide: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0

08-10 09:29:26.914   765   846 I ActivityManager: Displayed me.ccrama.redditslide/.Activities.MainActivity: +486ms (total +831ms)

08-10 09:29:40.122   765  4786 I ActivityManager: START u0 {cmp=me.ccrama.redditslide/.Activities.SubredditView (has extras)} from uid 10108

08-10 09:29:40.356   765   846 I ActivityManager: Displayed me.ccrama.redditslide/.Activities.SubredditView: +194ms

08-10 09:29:40.709 29090 29090 E AndroidRuntime: Process: me.ccrama.redditslide, PID: 29090

08-10 09:29:40.709 29090 29090 E AndroidRuntime: 	at me.ccrama.redditslide.SpoilerRobotoTextView.setSpoilerStyle(SpoilerRobotoTextView.java:726)

08-10 09:29:40.709 29090 29090 E AndroidRuntime: 	at me.ccrama.redditslide.SpoilerRobotoTextView.setTextHtml(SpoilerRobotoTextView.java:134)

08-10 09:29:40.709 29090 29090 E AndroidRuntime: 	at me.ccrama.redditslide.Views.CommentOverflow.setViews(CommentOverflow.java:146)

08-10 09:29:40.709 29090 29090 E AndroidRuntime: 	at me.ccrama.redditslide.Views.CommentOverflow.setViews(CommentOverflow.java:80)

08-10 09:29:40.709 29090 29090 E AndroidRuntime: 	at me.ccrama.redditslide.Activities.SubredditView.setViews(SubredditView.java:1827)

08-10 09:29:40.709 29090 29090 E AndroidRuntime: 	at me.ccrama.redditslide.Activities.SubredditView.doSubOnlyStuff(SubredditView.java:1273)

08-10 09:29:40.709 29090 29090 E AndroidRuntime: 	at me.ccrama.redditslide.Activities.SubredditView.access$800(SubredditView.java:98)

08-10 09:29:40.709 29090 29090 E AndroidRuntime: 	at me.ccrama.redditslide.Activities.SubredditView$AsyncGetSubreddit.onPostExecute(SubredditView.java:2090)

08-10 09:29:40.709 29090 29090 E AndroidRuntime: 	at me.ccrama.redditslide.Activities.SubredditView$AsyncGetSubreddit.onPostExecute(SubredditView.java:2079)

08-10 09:29:40.719   765  4783 W ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.SubredditView

08-10 09:29:40.722   765  4783 W ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.MainActivity

08-10 09:29:40.768   765   806 I ActivityManager: Showing crash dialog for package me.ccrama.redditslide u0

08-10 09:29:41.221   765   805 W ActivityManager: Activity pause timeout for ActivityRecord{6a7aa28 u0 me.ccrama.redditslide/.Activities.SubredditView t136 f}

08-10 09:29:42.603   765  4783 W ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.SubredditView

08-10 09:29:42.610   765  4783 W ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.MainActivity

08-10 09:29:42.633   765  4783 I ActivityManager: Killing 29090:me.ccrama.redditslide/u0a108 (adj 900): crash
```

If this log isn't enough, please tell me how to get a more detailed one. I cut the log to the part right after the login, since I don't know if the login tokens are personal stuff or not.

**Comment by edgato** [comment]
V5.9 alpha 2 crashes on /r/opensource

**Comment by Tensounder54** [comment]
I think these are edge cases as I can open them just fine in the latest build. We will keep an eye on thinks like this though. Ill leave it up to @Alexendoo if they want to close this issue or not.
