### ISSUE TITLE
Crash when collapsing any comment

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#284]
When tapping any comment to collapse it, the app crashes. 

Debug info:
 OS Version: 3.4.5-2679758(T110UEUANE4)
 OS API Level: 17
 Device: goyawifi
 Model (and Product): SM-T110 (goyawifiue)
 RELEASE: 4.2.2
 BRAND: samsung
 DISPLAY: JDQ39.T110UEUANE4
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: pxa988
 MANUFACTURER: samsung

Stacktrace: 

```
java.lang.StringIndexOutOfBoundsException: length=22, regionStart=0, regionLength=-1
	at java.lang.String.startEndAndLength(String.java:583)
	at java.lang.String.substring(String.java:1464)
	at me.ccrama.redditslide.Views.MakeTextviewClickable.ParseTextWithLinksTextViewComment(MakeTextviewClickable.java:116)
	at me.ccrama.redditslide.Adapters.CommentAdapter.onBindViewHolder(CommentAdapter.java:561)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5212)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5245)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4483)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1552)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:386)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14938)
	at android.view.ViewGroup.layout(ViewGroup.java:4601)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2212)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2026)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1236)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5160)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:561)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5365)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ccrama** [comment]
Has probably been fixed in latest few commits
