### ISSUE TITLE
Just tapped on a comment

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#286]
I went to /r/iamverysmart and then Slide crashed.

Debug info:
 OS Version: 3.4.42-gd8f2775(45)
 OS API Level: 19
 Device: peregrine
 Model (and Product): XT1045 (peregrine_att)
 RELEASE: 4.4.4
 BRAND: motorola
 DISPLAY: KXB21.14-L1.63
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: motorola

Stacktrace: 

```
java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 3529232 free bytes
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
	at android.content.res.Resources.loadDrawable(Resources.java:2113)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.widget.ImageView.<init>(ImageView.java:139)
	at android.widget.ImageButton.<init>(ImageButton.java:87)
	at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:60)
	at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:56)
	at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:110)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:926)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:980)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at me.ccrama.redditslide.Adapters.CommentAdapter.onCreateViewHolder(CommentAdapter.java:70)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5223)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4449)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:386)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14860)
	at android.view.ViewGroup.layout(ViewGroup.java:4643)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2013)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1770)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1019)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5725)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5086)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
```

**Comment by alexsmithfanning** [comment]
Just as another note; after I pressed "send" for this report, it crashed again.

**Comment by Alexendoo** [comment]
Send crash is most likely #243

**Comment by ccrama** [comment]
You ran out of RAM. Not really a way to fix this unfortunately except for future optimizations

**Comment by alexsmithfanning** [comment]
Not surprising. One gigabyte is hardly enough these days.
