### ISSUE TITLE
Opening a link from web

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#287]
I was on Google found a reddit post and tried to open it on slide and it crashed

Debug info:
 OS Version: 3.4.0-perf-g5c87ba0-02008-gbe52486(2925005669)
 OS API Level: 22
 Device: D6503
 Model (and Product): D6503 (D6503)
 RELEASE: 5.1.1
 BRAND: Sony
 DISPLAY: 23.4.A.1.232
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: Sony

Stacktrace: 

```java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at me.ccrama.redditslide.Adapters.CommentAdapter.reset(CommentAdapter.java:130)
	at me.ccrama.redditslide.Fragments.CommentPage.doData(CommentPage.java:259)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.onPostExecute(SubmissionComments.java:74)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.onPostExecute(SubmissionComments.java:60)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by l3d00m** [comment]
same as #264
