### ISSUE TITLE
Crash whilst attempting to change posts

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#289]
crashed while attempting to change posts.

Debug info:
 OS Version: 3.10.61-5527015(G925AUCU3BOI2)
 OS API Level: 22
 Device: zerolteatt
 Model (and Product): SAMSUNG-SM-G925A (zerolteuc)
 RELEASE: 5.1.1
 BRAND: samsung
 DISPLAY: LMY47X.G925AUCU3BOI2
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: samsungexynos7420
 MANUFACTURER: samsung

Stacktrace: 

```
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 50, found: 75 Pager id: me.ccrama.redditslide:id/contentView Pager class: class android.support.v4.view.ViewPager Problematic adapter: class me.ccrama.redditslide.Activities.CommentsScreen$OverviewPagerAdapter
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1000)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
	at android.view.View.measure(View.java:18849)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.view.View.measure(View.java:18849)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
	at android.view.View.measure(View.java:18849)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18849)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.view.View.measure(View.java:18849)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18849)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.view.View.measure(View.java:18849)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at android.view.View.measure(View.java:18849)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5904)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3073)
	at android.view.View.measure(View.java:18849)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2342)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1379)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1622)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1264)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6944)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6837)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by l3d00m** [comment]
same as #153
