### ISSUE TITLE
Hiding the comment action bar after voting can cause a crash

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#291]
Hui

Debug info:
 OS Version: 3.4.0-g17207298(509530.6)
 OS API Level: 21
 Device: htc_m8
 Model (and Product): HTC One_M8 (h3g_uk)
 RELEASE: 5.0.2
 BRAND: htc
 DISPLAY: LRX22G release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: HTC

Stacktrace: 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference
	at android.support.design.widget.Snackbar.<init>(Snackbar.java:180)
	at android.support.design.widget.Snackbar.make(Snackbar.java:206)
	at me.ccrama.redditslide.Vote$1.run(Vote.java:52)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5696)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by Alexendoo** [comment]
Helpful as ever

**Comment by ccrama** [comment]
Really people. This is getting out of hand.

**Comment by l3d00m** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at android.support.design.widget.Snackbar.<init>(Snackbar.java:180)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at android.support.design.widget.Snackbar.make(Snackbar.java:206)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at android.support.design.widget.Snackbar.make(Snackbar.java:231)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at me.ccrama.redditslide.Vote$1.run(Vote.java:52)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5349)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
10-27 19:48:32.602 19818-19818/me.ccrama.redditslide E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

Test if same
