### ISSUE TITLE
Crashed trying to restore backup settings

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#292]
Backup were made on 4.4 tablet, trying to back up to Android 5.1 phone

Debug info:
 OS Version: 3.4.0-CM-g753464a(3449be6888)
 OS API Level: 22
 Device: d855
 Model (and Product): LG-D855 (g3_global_com)
 RELEASE: 5.1.1
 BRAND: lge
 DISPLAY: cm_d855-userdebug 5.1.1 LVY48F 3449be6888 test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: g3
 MANUFACTURER: LGE

Stacktrace: 

```java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: Cannot use setProgress() on this dialog.
	at com.afollestad.materialdialogs.MaterialDialog.setProgress(MaterialDialog.java:1534)
	at me.ccrama.redditslide.Activities.SettingsBackup$RetrieveDriveFileContentsAsyncTask.doInBackground(SettingsBackup.java:301)
	at me.ccrama.redditslide.Activities.SettingsBackup$RetrieveDriveFileContentsAsyncTask.doInBackground(SettingsBackup.java:260)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by ccrama** [comment]
Dupe.
