### ISSUE TITLE
Crash upon changing from "Top" to "Hot"

### ISSUE THREAD

**Issue by Snagg57** [ccrama/Slide#303]
While in comments Slide crashed while attempting to change comment filtering mode.

Debug info:
 OS Version: 3.10.40-geec2459(1860966)
 OS API Level: 22
 Device: shamu
 Model (and Product): Nexus 6 (shamu)
 RELEASE: 5.1.1
 BRAND: google
 DISPLAY: LMY47Z
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: shamu
 MANUFACTURER: motorola

Stacktrace: 

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{19abcd2 position=34 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent}
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4247)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4378)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:386)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by ccrama** [comment]
Fixed. 8756edc3ccd4e55f86c69f72d941e42b3c61467f
