### ISSUE TITLE
[Slide][v6.2 ]App failed to open

### ISSUE THREAD

**Issue by 44asad** [ccrama/Slide#3030]
### Actual behavior

App crashing again and again ,can not open the app.
### Expected behavior

Expected that i can open the app and can use successfully

### How to reproduce:
1.Download the app.
2.Then Open the application
6.Note the Bug.

### information
* App version:v6.2
* os:Android 6.0.1
* Device:samsung J5
### Recording of the bug

https://youtu.be/CAMYGPPM79w

### Logcat:
<pre><code>06-29 07:57:24.562  6308  6308 E AndroidRuntime: FATAL EXCEPTION: main
06-29 07:57:24.562  6308  6308 E AndroidRuntime: Process: me.ccrama.redditslide, PID: 6308
06-29 07:57:24.562  6308  6308 E AndroidRuntime: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class ImageView
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at me.ccrama.redditslide.Activities.Tutorial$Welcome.onCreateView(Tutorial.java:104)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:168)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.view.ViewPager.populate(ViewPager.java:1244)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.View.measure(View.java:20190)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.View.measure(View.java:20190)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.View.measure(View.java:20190)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.View.measure(View.java:20190)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.View.measure(View.java:20190)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.View.measure(View.java:20190)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3094)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.View.measure(View.java:20190)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2643)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1598)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1890)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1486)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7467)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.Choreographer.doCallbacks(Choreographer.java:695)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.Choreographer.doFrame(Choreographer.java:631)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
06-29 07:57:24.562  6308  6308 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)</code></pre>

**Comment by 44asad** [comment]
@Tensounder54

**Comment by Tensounder54** [comment]
Hay there. Thanks for making such a clear bug report. After looking through the Log, its pretty clear that this issue is a runtime error in the tutorial class. I've never encountered this issue before but it's something we will look into ASAP. As a remedial attempt, have you tried uninstallkng and reinstalling?
