### ISSUE TITLE
Crash on launch (6.2.2)

### ISSUE THREAD

**Issue by TacoTheDank** [ccrama/Slide#3049]
Slide version: 6.2.2
Android version: 9.0 Pie (Model: SM-N960U)

This is happening right after upgrading the app version. Clearing data didn't do anything.
```
FATAL EXCEPTION: main
Process: me.ccrama.redditslide, PID: 20372
android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class ImageView
Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class ImageView
Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f080128
Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080128
	at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:267)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:831)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:677)
	at android.content.res.Resources.loadDrawable(Resources.java:912)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.widget.ImageView.<init>(ImageView.java:189)
	at android.widget.ImageView.<init>(ImageView.java:172)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
	at android.support.v7.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:182)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
	at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
	at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at me.ccrama.redditslide.Activities.Tutorial$Welcome.onCreateView(Tutorial.java:104)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:168)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1244)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:24940)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:24940)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7127)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:24940)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7127)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:24940)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7127)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:24940)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7127)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:24940)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7127)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:993)
	at android.view.View.measure(View.java:24940)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3263)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1990)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2292)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1850)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by Alexendoo** [comment]
Weird, not much change between https://github.com/ccrama/Slide/compare/6.2.1...6.2.2, does this work for you on Pie @timawesomeness?

**Comment by Tensounder54** [comment]
I can't replicate this bug myself. I haven't had a crash from slide in a while.

**Comment by TacoTheDank** [comment]
Actually, this was caused by a mistake on my own end. No need to worry about this one
