### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#305]
on start

Debug info:
 OS Version: 3.4.0-perf-gf95c7ee(1421650137)
 OS API Level: 21
 Device: g3
 Model (and Product): LG-D855 (g3_global_com)
 RELEASE: 5.0
 BRAND: lge
 DISPLAY: ChupaChups ROM v.4.2
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: g3
 MANUFACTURER: LGE

Stacktrace: 

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
	at me.ccrama.redditslide.Activities.SubredditOverview$11.onClick(SubredditOverview.java:333)
	at android.view.View.performClick(View.java:4763)
	at android.view.View$PerformClick.run(View.java:19821)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5274)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```

**Comment by ccrama** [comment]
Fixed 7ce637e58c930fc81e5ce29bead5b38a9ca6ac08
