### ISSUE TITLE
[META] Connectivity Crashes under Various Circumstances

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#306]
Merging all the various "Crashed on connection" issues into this one.

**Comment by l3d00m** [comment]
```
java.lang.RuntimeException: Could not execute the request: HttpRequest {method='GET', url=https://oauth.reddit.com/subreddits/mine/moderator?limit=100, expectedMediaType=application/json, headers=User-Agent: android:me.ccrama.RedditSlide:v4.311-30 20:07:50.213 12763-12900/me.ccrama.redditslide W/System.err: Authorization: bearer 32719971-rY2bynJkQdptSVFT7takWKOOkk011-30 20:07:50.213 12763-12900/me.ccrama.redditslide W/System.err: Cache-Control: no-cache11-30 20:07:50.213 12763-12900/me.ccrama.redditslide W/System.err: , body=null}11-30 20:07:50.213 12763-12900/me.ccrama.redditslide W/System.err:
at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
11-30 20:07:50.213 12763-12900/me.ccrama.redditslide W/System.err:
at net.dean.jraw.RedditClient.execute(RedditClient.java:150)
11-30 20:07:50.213 12763-12900/me.ccrama.redditslide W/System.err:
at net.dean.jraw.RedditClient.execute(RedditClient.java:144)
11-30 20:07:50.213 12763-12900/me.ccrama.redditslide W/System.err:
at net.dean.jraw.paginators.Paginator.next(Paginator.java:109)
11-30 20:07:50.213 12763-12900/me.ccrama.redditslide W/System.err:
at net.dean.jraw.paginators.UserSubredditsPaginator.next(UserSubredditsPaginator.java:44)
11-30 20:07:50.213 12763-12900/me.ccrama.redditslide W/System.err:
at net.dean.jraw.paginators.Paginator.next(Paginator.java:70)
11-30 20:07:50.214 12763-12900/me.ccrama.redditslide W/System.err:
at me.ccrama.redditslide.SubredditStorage.doModOf(SubredditStorage.java:351)
11-30 20:07:50.214 12763-12900/me.ccrama.redditslide W/System.err:
at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:200)
11-30 20:07:50.214 12763-12900/me.ccrama.redditslide W/System.err:
at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:27)
11-30 20:07:50.214 12763-12900/me.ccrama.redditslide W/System.err:
at android.os.AsyncTask$2.call(AsyncTask.java:288)
11-30 20:07:50.214 12763-12900/me.ccrama.redditslide W/System.err:
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-30 20:07:50.214 12763-12900/me.ccrama.redditslide W/System.err:
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
11-30 20:07:50.214 12763-12900/me.ccrama.redditslide W/System.err:
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-30 20:07:50.214 12763-12900/me.ccrama.redditslide W/System.err:
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-30 20:07:50.214 12763-12900/me.ccrama.redditslide W/System.err:
at java.lang.Thread.run(Thread.java:818)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err: Caused by: java.net.UnknownHostException: Unable to resolve host "oauth.reddit.com": No address associated with hostname11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at java.net.InetAddress.lookupHostByName(InetAddress.java:482)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at java.net.InetAddress.getAllByNameImpl(InetAddress.java:255)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at java.net.InetAddress.getAllByName(InetAddress.java:218)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
11-30 20:07:50.215 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.Call.getResponse(Call.java:271)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err:
at com.squareup.okhttp.Call.execute(Call.java:79)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err:
at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err:
at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err: 	... 14 more11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err:
at libcore.io.Posix.android_getaddrinfo(Native Method)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err:
at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err:
at java.net.InetAddress.lookupHostByName(InetAddress.java:446)
11-30 20:07:50.216 12763-12900/me.ccrama.redditslide W/System.err: 	... 30 more
```

**Comment by l3d00m** [comment]
Can we assume that this is fixed now because of the offline update?

**Comment by Alexendoo** [comment]
Sounds good to me. If there are any specific examples that pop up they're going to be far less frequent than it used to be, so they can have their own issue #
