### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by dickyharper** [ccrama/Slide#3086]
Slide version:6.2.2
Android version:5

**Comment by dickyharper** [comment]
![Screenshot_2019-12-10-15-45-52](https://user-images.githubusercontent.com/50758669/70530658-701f4b00-1b64-11ea-8f68-77c8955ff924.png)
![Screenshot_2019-12-10-15-45-58](https://user-images.githubusercontent.com/50758669/70530675-79101c80-1b64-11ea-941d-aee4b641a621.png)
![Screenshot_2019-12-10-15-46-04](https://user-images.githubusercontent.com/50758669/70530699-83cab180-1b64-11ea-9f04-2111567166ac.png)
![Screenshot_2019-12-10-15-46-11](https://user-images.githubusercontent.com/50758669/70530709-8d541980-1b64-11ea-9761-b21c7796e5d2.png)
![Screenshot_2019-12-10-15-46-16](https://user-images.githubusercontent.com/50758669/70530720-9644eb00-1b64-11ea-9a61-ee6d026b5d04.png)

**Comment by Alexendoo** [comment]
Thanks for the trace @dickyharper, could you paste it as text rather than screenshots? That would help out a lot if so

**Comment by dickyharper** [comment]
`﻿java.lang.OutOfMemoryError: Failed to
allocate a 1327116 byte allocation with
1280914 free bytes and 1250KB until OOM
at
dalvik.system.VM Runtime.newNonMovable
Array(Native Method)
at
android.graphics.BitmapFactory.nativeDec
odeAsset(Native Method)
at
android.graphics.BitmapFactory.decodeStr
eam(BitmapFactory.java:747)
at
android.graphics.BitmapFactory.decodeRe
sourceStream(BitmapFactory.java:568)
at
android.graphics.drawable.Drawable.creat
eFromResourceStream(Drawable.java:
1014)
at
android.content.res.Resources.loadDrawab
leForCookie(Resources.java:3747)
at
android.content.res.Resources.loadDrawab
le(Resources.java:3620)
at
android.content.res.Resources.getDrawabl
e(Resources.java:1852)
at
android.content.Context.getDrawable(Con
text.java:408)
 ﻿at
android.support.v4.content.ContextCompa
t.getDrawable(ContextCompat.java:463)
at
android.support.v7.widget.AppCompatDra
wableManager.getDrawable(AppCompatDr
awableManager.java:203)
at
android.support.v7.widget.AppCompatDra
wableManager.getDrawable(AppCompatDr
awableManager.java:191)
at
android.support.v7.content.res.AppCompa
tResources.getDrawable(AppCompatReso
urces.java:102)
at
android.supportv7.widget.AppCompatlma
geHelper.loadFromAttributes(AppCompatl
mageHelper.java:59)
at
android.support.v7.widget.AppCompatlma
geView.<init>(AppCompatlmageView.java:
78)
at
android.support.v7.widget.AppCompatlma
geView.<init>(AppCompatlmageView.java:
68)
at
android.support.v7.app.AppCompatViewln
flater.createlmageView(AppCompatViewln
flater.java:182)
 ﻿at
android.support.v7.app.AppCompatViewln
flater.createView(AppCompatViewlnflater.j
ava:106)
at
android.support.v7.app.AppCompatDelega
telmpl.createView(AppCompatDelegatelm
pl.java:1266)
at
android.support.v7.app.AppCompatDelega
telmpl.onCreateView(AppCompatDelegate
lmpl.java:1316)
at
android.view.Layoutlnflater.createViewFro
mTag(Layoutlnflater.java:732)
at
android.view.Layoutlnflater.rlnflate(Layoutl
nflater.java:813)
at
android.view.Layoutlnflater.rlnflate(Layoutl
nflater.java:821)
at
android.view.Layoutlnflater.rlnflate(Layoutl
nflater.java:821)
at
android.view.Layoutlnflater.inflate(Layoutl
nflater.java:511)
at
android.view.Layoutlnflater.inflate(Layoutl
nflater.java:415)
at
 ﻿me.ccrama.redditslide.Adapters.Comment
Adapter.onCreateViewhlolder(CommentAd
apter.java:194)
at
android.support.v7.widget.RecyclerView
$Adapter.createViewHolder(RecyclerView.j
ava:6794)
at
android.support.v7.widget.RecyclerView
$Recycler.tryGetViewHolderForPositionBy
Deadline(RecyclerView.java:5975)
at
android.support.v7.widget.RecyclerView
$Recycler.getViewForPosition(RecyclerVie
w.java:5858)
at
android.support.v7.widget.RecyclerView
$Recycler.getViewForPosition(RecyclerVie
w.java:5854)
at
android.support.v7.widget.LinearLayoutMa
nager
$LayoutState.next(LinearLayoutManager.ja
va:2230)
at
android.support.v7.widget.LinearLayoutMa
nager.layoutChunk(LinearLayoutManager.j
ava:1557)
at
android.support.v7.widget.LinearLayoutMa
nager.fill(LinearLayoutManager.java:1517)
 ﻿at
android.support.v7.widget.LinearLayoutMa
nager.onLayoutChildren(LinearLayoutMan
ager.java:612)
at
me.ccrama.redditslide.Views.PreCachingLa
youtManagerComments.onLayoutChildren
(PreCachingLayoutManagerComments.jav
a:19)
at
android.supportv7.widget.RecyclerView.di
spatchLayoutStep2(RecyclerView.java:
3924)
at
android.support.v7.widget.RecyclerView.di
spatchLayout(RecyclerView.java:3641)
at
android.support.v7.widget.RecyclerView.on
Layout(RecyclerVi ew.java :4194)
atandroid.view.View.layout(View.java:
16695)
at
android.view.ViewGroup.layout(ViewGroup.
java:5328)
at
android.support.v4.widget.SwipeRefreshLa
yout.onLayout(SwipeRefreshLayout.java:
625)
atandroid.view.View.layout(View.java:
16695)
at`

**Comment by dickyharper** [comment]
`﻿java.lang.OutOfMemoryError: Failed to
allocate a 9437196 byte allocation with
9146058 free bytes and 8MB until OOM
at
dalvik.system.VM Runtime.newNonMovable
Array(Native Method)
at
android.graphics.BitmapFactory.nativeDec
odeAsset(Native Method)
at
android.graphics.BitmapFactory.decodeStr
eam(BitmapFactory.java:747)
at
android.graphics.BitmapFactory.decodeRe
sourceStream(BitmapFactory.java:568)
at
android.graphics.BitmapFactory.decodeRe
source(BitmapFactory.java:596)
at
android.graphics.BitmapFactory.decodeRe
source(BitmapFactory.java:626)
at
me.ccrama.redditslide.Activities.BaseActiv
ity.setRecentBar(BaseActivity.java:486)
at
me.ccrama.redditslide.Activities.BaseActiv
ity.setRecentBar(BaseActivity.java:437)
at
me.ccrama.redditslide.Activities.MainActiv
ity.doPage5electedComments(MainActivit
y.java:2354)
 ﻿at
me.ccrama.redditslide.Activities.MainActiv
ity$OverviewPagerAdapterComment
$1.onPageScrolled(MainActivity.java:5176)
at
android.support.v4.view.ViewPager.dispatc
hOnPage5crolled(ViewPager.java:1930)
at
android.support.v4.view.ViewPager.onPage
Scrolled(ViewPager.java:1904)
at
android.support.v4.view.ViewPager.pageScr
olled(ViewPager.java:1842)
at
android.support.v4.view.ViewPager.scrollTo
ltem(ViewPager.java:694)
at
android.support.v4.view.ViewPager.setCurr
entltemlnternal(ViewPager.java:670)
at
android.support.v4.view.ViewPager.setCurr
entltemlnternal(ViewPager.java:631)
at
android.support.v4.view.ViewPager.dataSet
Changed(ViewPager.java:1086)
atandroid.support.v4.view.ViewPager
$PagerObserver.onChanged(ViewPager.jav
a:3097)
at
android.support.v4.view.PagerAdapter.noti﻿fyData5etChanged(PagerAdapter.java:291)
at
me.ccrama.redditslide.Adapters.Submissio
nAdapter
$4.on5ingleClick(SubmissionAdapter.java:
231)
at
me.ccrama.redditslide.util.OnSingleClickLi
stener.onClick(On5ingleClickListener.java:
40)
at
android.view.View.performClick(View.java:
5184)
at android.view.View
$PerformClick.run(View.java:20910)
at
android.os.Handler.handleCallback(Handler
.java:739)
at
android.os.hlandler.dispatchMessage(Hand
ler.java:95)
atandroid.os.Looper.loop(Looper.java:
145)
at
android.app.ActivityThread.main(ActivityT
hread.java:5951)
at Java.lang.reflect.Method.invoke(Native
Method)
at
java.lang.reflect.Method.invoke(Method.jav
a:372)
 ﻿me.ccrama.redditslide.util.OnSingleClickLi
stener.onClick(OnSingleClickListener.java:
40)
at
android.view.View.performClick(View.java:
5184)
at android.view.View
$PerformClick.run(View.java:20910)
at
android.os.Handler.handleCallback(Handler
.java:739)
at
android.os.hlandler.dispatchMessage(Hand
ler.java:95)
atandroid.os.Looper.loop(Looper.java:
145)
at
android.app.ActivityThread.main(ActivityT
hread.java:5951)
atjava.lang.reflect.Method.invoke(Native
Method)
at
java.lang.reflect.Method.invoke(Method.jav
a:372)
atcom.android.internal.os.Zygotelnit
$MethodAndArgsCaller.run(Zygotelnit.java
: 1400)
at
com.android.internal.os.Zygotelnit.main(Zy
gotelnitjava:n95)`

**Comment by dickyharper** [comment]
`java.lang.OutOfMemoryError: Failed to
allocate a 9437196 byte allocation with
8755812 free bytes and 8MB until OOM
at
dalvik.system.VMRuntime.newNonMovabl
eArray(Native Method)
at
android.graphics.BitmapFactory.nativeDec
odeAsset(Native Method)
at
android.graphics.BitmapFactory.decodeStr
eam(BitmapFactory.java:747)
at
android.graphics.BitmapFactory.decodeRe
sourceStream(BitmapFactory.java:568)
at
android.graphics.BitmapFactory.decodeRe
source(BitmapFactory.java:596)
at
android.graphics.BitmapFactory.decodeRe
source(BitmapFactory.java:626)
at
me.ccrama.redditslide.Activities.BaseActivi
ty.setRecentBar(BaseActivity.java:486)
at
me.ccrama.redditslide.Activities.FullScreen
Activity.onCreate(FullScreenActivity.java:
32)
at
me.ccrama.redditslide.Activities.MediaVie
w.onCreate(MediaView.java:592)
at
android.app.Activity.performCreate(Activity
-java:6289)
at
android.app.lnstrumentation.callActivityOn
Create(lnstrumentation.java:1119)
at
android.app.ActivityThread.performLaunch
Activity(ActivityThread.java:2655)
at
android.app.ActivityThread.handleLaunchA
ctivity(ActivityThread.java:2767)
at android.app.ActivityThread.access
$900(ActivityThread.java:177)
at android.app.ActivityThread
$H.handleMessage(ActivityThread.java:
1449)
at
android.os.Handler.dispatchMessage(Han
dler.java:102)
atandroid.os.Looper.loop(Looper.java:
145)
at
android.app.ActivityThread.main(ActivityTh
read.java:5951)
atjava.lang.reflect.Method.invoke(Native
Method)
at
java.lang.reflect.Method.invoke(Method.jav
a:372)
at com. android. internal, os. Zygotelnit
$MethodAndArgsCaller.run(Zygotelnit.java:
1400)
at
com.android.internal.os.Zygotelnit.main(Zy
gotelnit.java:1195)`

**Comment by dickyharper** [comment]
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@6aa9c88
versionCode=322
BOARD=universal5410
IS_TRANSLATION_ASSISTANT_ENABLED=false
BOOTLOADER=I9500XXUHPJ3
TYPE=user
ID=LRX22C
TIME=1476692115000
BRAND=samsung
TAG=Build
SERIAL=4d00b642d0e722ed
HARDWARE=universal5410
SUPPORTED_ABIS=[Ljava.lang.String;@2b864621
CPU_ABI=armeabi-v7a
IS_DEBUGGABLE=false
RADIO=unknown
MANUFACTURER=samsung
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@9c0402b
isOSUpgradeKK2LL=true
IS_SYSTEM_SECURE=false
TAGS=release-keys
CPU_ABI2=armeabi
UNKNOWN=unknown
USER=dpi
FINGERPRINT=samsung/ja3gxx/ja3g:5.0.1/LRX22C/I9500XXUHPJ3:user/release-keys
FOTA_INFO=1476692039
HOST=SWDD6805
PRODUCT=ja3gxx
versionName=6.2.2
DISPLAY=LRX22C.I9500XXUHPJ3
MODEL=GT-I9500
DEVICE=ja3g
IS_SECURE=false
java.lang.OutOfMemoryError: Failed to allocate a 9437196 byte allocation with 5410054 free bytes and 5MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:747)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:568)
	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:596)
	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:626)
	at me.ccrama.redditslide.Activities.BaseActivity.setRecentBar(BaseActivity.java:486)
	at me.ccrama.redditslide.Activities.BaseActivity.setRecentBar(BaseActivity.java:437)
	at me.ccrama.redditslide.Activities.SubredditView$OverviewPagerAdapterComment$1.onPageScrolled(SubredditView.java:1992)
	at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1930)
	at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1904)
	at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1842)
	at android.support.v4.view.ViewPager.computeScroll(ViewPager.java:1802)
	at android.view.View.updateDisplayListIfDirty(View.java:15113)
	at android.view.View.getDisplayList(View.java:15149)
	at android.view.View.draw(View.java:15924)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
	at android.view.View.updateDisplayListIfDirty(View.java:15121)
	at android.view.View.getDisplayList(View.java:15149)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
	at android.view.View.updateDisplayListIfDirty(View.java:15086)
	at android.view.View.getDisplayList(View.java:15149)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
	at android.view.View.updateDisplayListIfDirty(View.java:15086)
	at android.view.View.getDisplayList(View.java:15149)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
	at android.view.View.updateDisplayListIfDirty(View.java:15086)
	at android.view.View.getDisplayList(View.java:15149)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
	at android.view.View.updateDisplayListIfDirty(View.java:15086)
	at android.view.View.getDisplayList(View.java:15149)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
	at android.view.View.updateDisplayListIfDirty(View.java:15086)
	at android.view.View.getDisplayList(View.java:15149)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
	at android.view.View.updateDisplayListIfDirty(View.java:15086)
	at android.view.View.getDisplayList(View.java:15149)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
