### ISSUE TITLE
App wasn't used in ages and suddenly it reports to have crashed.

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#311]
App wasn't used in a few days, at least for a day and then suddenly a crash report.

Debug info:
 OS Version: 3.10.49-perf+(17)
 OS API Level: 22
 Device: OnePlus2
 Model (and Product): ONE A2003 (OnePlus2)
 RELEASE: 5.1.1
 BRAND: OnePlus
 DISPLAY: ONE A2003_14_150919
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: qcom
 MANUFACTURER: OnePlus

Stacktrace: 

```java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: net.dean.jraw.http.NetworkException: Request returned non-successful status code: 403 Forbidden
	at net.dean.jraw.http.RestClient.execute(RestClient.java:132)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.paginators.Paginator.next(Paginator.java:109)
	at net.dean.jraw.paginators.SubredditPaginator.next(SubredditPaginator.java:53)
	at net.dean.jraw.paginators.Paginator.next(Paginator.java:70)
	at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:150)
	at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:27)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by l3d00m** [comment]
merge in #306
