### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by dickyharper** [ccrama/Slide#3126]
Slide version: 6.3
Android version: 5.0.1 
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@3902a4d1
versionCode=323
BOARD=universal5410
IS_TRANSLATION_ASSISTANT_ENABLED=false
BOOTLOADER=I9500XXUHPJ3
TYPE=user
ID=LRX22C
TIME=1476692115000
BRAND=samsung
TAG=Build
SERIAL=4d00b642d0e722ed
HARDWARE=universal5410
SUPPORTED_ABIS=[Ljava.lang.String;@1efe0b36
CPU_ABI=armeabi-v7a
IS_DEBUGGABLE=false
RADIO=unknown
MANUFACTURER=samsung
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@10d787f8
isOSUpgradeKK2LL=true
IS_SYSTEM_SECURE=false
TAGS=release-keys
CPU_ABI2=armeabi
UNKNOWN=unknown
USER=dpi
FINGERPRINT=samsung/ja3gxx/ja3g:5.0.1/LRX22C/I9500XXUHPJ3:user/release-keys
FOTA_INFO=1476692039
HOST=SWDD6805
PRODUCT=ja3gxx
versionName=6.3
DISPLAY=LRX22C.I9500XXUHPJ3
MODEL=GT-I9500
DEVICE=ja3g
IS_SECURE=false
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 11190284 byte allocation with 10927486 free bytes and 10MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:773)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:749)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:477)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:61)
	at me.ccrama.redditslide.Views.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1668)
	at me.ccrama.redditslide.Views.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1639)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
java.lang.OutOfMemoryError: Failed to allocate a 11190284 byte allocation with 10927486 free bytes and 10MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:773)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:749)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:477)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:61)
	at me.ccrama.redditslide.Views.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1668)
	at me.ccrama.redditslide.Views.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1639)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by Tensounder54** [comment]
Please can you provide more context to this? What were you doing at the time?

**Comment by dickyharper** [comment]
> Please can you provide more context to this? What were you doing at the time?
I sent a message to someone about Termux app from pm.  Then it crashed when switched to FrontPage.  That's all.
