### ISSUE TITLE
Refreshing any subreddit causes slide to crash

### ISSUE THREAD

**Issue by Fernando-UofT** [ccrama/Slide#317]
as the title says

Debug info:
 OS Version: 3.10.40-gc16a3c6(2167285)
 OS API Level: 22
 Device: shamu
 Model (and Product): Nexus 6 (shamu)
 RELEASE: 5.1.1
 BRAND: google
 DISPLAY: LMY48M
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: shamu
 MANUFACTURER: motorola
 SLIDE VERSION: 72

Stacktrace: 

```java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:25).state:25
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4401)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1034)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:744)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1180)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:757)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ccrama** [comment]
Fixed 69c0ef81c58fe5bd14530264604e9f9ec0e36bca
