### ISSUE TITLE
Crash when subscribing to Android subreddit

### ISSUE THREAD

**Issue by atharvalele** [ccrama/Slide#318]
ticked the subscribe option and it crashed

Debug info:
 OS Version: 3.4.42-gb476356(3)
 OS API Level: 22
 Device: ghost
 Model (and Product): XT1052 (ghost_retasia)
 RELEASE: 5.1
 BRAND: motorola
 DISPLAY: LPA23.12-15.5
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: motorola
 SLIDE VERSION: 72

Stacktrace: 

```android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1161)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:749)
	at okio.Okio$1.write(Okio.java:78)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:201)
	at com.squareup.okhttp.internal.spdy.Spdy3$Writer.synStream(Spdy3.java:339)
	at com.squareup.okhttp.internal.spdy.SpdyConnection.newStream(SpdyConnection.java:266)
	at com.squareup.okhttp.internal.spdy.SpdyConnection.newStream(SpdyConnection.java:242)
	at com.squareup.okhttp.internal.http.SpdyTransport.writeRequestHeaders(SpdyTransport.java:89)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:814)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
	at com.squareup.okhttp.Call.getResponse(Call.java:272)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
	at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.managers.AccountManager.setSubscribed(AccountManager.java:266)
	at net.dean.jraw.managers.AccountManager.unsubscribe(AccountManager.java:255)
	at me.ccrama.redditslide.Activities.SubredditView$8.onCheckedChanged(SubredditView.java:620)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:154)
	at android.widget.CompoundButton.toggle(CompoundButton.java:113)
	at android.widget.CompoundButton.performClick(CompoundButton.java:118)
	at android.view.View$PerformClick.run(View.java:19884)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by l3d00m** [comment]
merge in #343
