### ISSUE TITLE
Force close on subreddit refresh

### ISSUE THREAD

**Issue by matthieugrieger** [ccrama/Slide#319]
After choosing a subreddit to browse (in this case it was /r/askreddit) and pulling down to refresh, the app force closes. Happens in single mode as well as the normal mode.

Debug info:
 OS Version: 3.10.49-perf-ge36128e(18)
 OS API Level: 22
 Device: clark
 Model (and Product): XT1575 (clark_retus)
 RELEASE: 5.1.1
 BRAND: motorola
 DISPLAY: LPH23.116-18
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: qcom
 MANUFACTURER: motorola
 SLIDE VERSION: 72

Stacktrace: 

```java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:27).state:27
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4401)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1034)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:744)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1180)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:757)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15689)
	at android.view.ViewGroup.layout(ViewGroup.java:5041)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2116)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by matthieugrieger** [comment]
Closed as there are already multiple issues reporting the same thing.
