### ISSUE TITLE
Crash when refresh subreddit

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#326]
title

Debug info:
 OS Version: 3.1.10-g535135e(ea38de797e)
 OS API Level: 22
 Device: enrc2b
 Model (and Product): One X+ (enrc2b)
 RELEASE: 5.1.1
 BRAND: htc_europe
 DISPLAY: cm_enrc2b-userdebug 5.1.1 LMY48W ea38de797e test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: enrc2b
 MANUFACTURER: HTC
 SLIDE VERSION: 72

Stacktrace: 

```java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:25).state:25
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4401)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2864)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1034)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:744)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1180)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:757)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by ccrama** [comment]
Fixed in latest commit
