### ISSUE TITLE
Slide crashed on opening settings

### ISSUE THREAD

**Issue by Korpip** [ccrama/Slide#329]
Was very sad.

Debug info:
 OS Version: 3.4.0-ElementalX-N7-4.05(2002b1d80c)
 OS API Level: 22
 Device: flo
 Model (and Product): Nexus 7 (razor)
 RELEASE: 5.1.1
 BRAND: Google
 DISPLAY: screwd_flo-userdebug 5.1.1 LVY48F 2002b1d80c test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: flo
 MANUFACTURER: Asus
 SLIDE VERSION: 73

Stacktrace: 

```java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.Settings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2430)
	at android.app.ActivityThread.access$900(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5321)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:375)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at me.ccrama.redditslide.Activities.Settings.onCreate(Settings.java:205)
	at android.app.Activity.performCreate(Activity.java:6865)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
	... 10 more
```

**Comment by Alexendoo** [comment]
Should be fixed by b09b3d2f7a7a2b18ecf68b6a053de20826451e3e
