### ISSUE TITLE
Subreddit search doesn't work.

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#330]
when searching for a subreddit it just reloads the front page.

Debug info:
 OS Version: 3.10.40-g909db78(2256973)
 OS API Level: 23
 Device: flounder
 Model (and Product): Nexus 9 (volantis)
 RELEASE: 6.0
 BRAND: google
 DISPLAY: MRA58K
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: flounder
 MANUFACTURER: htc
 SLIDE VERSION: 73

Stacktrace: 

```android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class <unknown>
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at me.ccrama.redditslide.Adapters.CommentAdapter$15.onClick(CommentAdapter.java:812)
	at android.view.View.performClick(View.java:5198)
	at android.view.View$PerformClick.run(View.java:21147)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	... 17 more
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f01028f a=-1}
	at android.content.res.TypedArray.getColor(TypedArray.java:447)
	at android.support.v7.widget.CardView.initialize(CardView.java:205)
	at android.support.v7.widget.CardView.<init>(CardView.java:101)
	... 19 more
```

**Comment by ccrama** [comment]
Cannot reproduce

**Comment by l3d00m** [comment]
can we assume that this is fixed and or obsolete now?

**Comment by Alexendoo** [comment]
Old & unconfirmed, if it's still occurring for anybody comment/reopen/create a new issue

**Comment by l3d00m** [comment]
it isn't any longer happening for me, i had the issue too
