### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by emacsomancer** [ccrama/Slide#338]
crashed when adding 2nd account 

Debug info:
 OS Version: 3.4.0-g6af28ec(448934.10)
 OS API Level: 21
 Device: htc_m8
 Model (and Product): HTC One M8 (htc_europe)
 RELEASE: 5.0.2
 BRAND: htc
 DISPLAY: LRX22G release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: HTC
 SLIDE VERSION: 73

Stacktrace: 

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='GET', url=https://oauth.reddit.com/api/v1/me, expectedMediaType=application/json, headers=User-Agent: android:me.ccrama.RedditSlide:v4.0 (by /u/ccrama)
Authorization: bearer 
, body=null}
	at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.RedditClient.me(RedditClient.java:240)
	at net.dean.jraw.RedditClient.authenticate(RedditClient.java:123)
	at me.ccrama.redditslide.Authentication$UpdateToken.doInBackground(Authentication.java:74)
	at me.ccrama.redditslide.Authentication$UpdateToken.doInBackground(Authentication.java:53)
	at android.os.AsyncTask$2.call(AsyncTask.java)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Caused by: java.net.UnknownHostException: Unable to resolve host "oauth.reddit.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
	at java.net.InetAddress.getAllByName(InetAddress.java:215)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
	at java.net.InetAddress.getAllByName(<Xposed>)
	at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
	at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
	at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
	at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
	... 12 more
```

**Comment by ccrama** [comment]
You were disconnected from the internet somehow while adding account. Merging with #306

**Comment by emacsomancer** [comment]
Probably because of a VPN connectoin.

ccrama <notifications@github.com> writes:

> You were disconnected from the internet somehow while adding account. Merging with #306 
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ccrama/Slide/issues/338#issuecomment-153032430


-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dr Benjamin Slade
pgp fingerprint: 21BA 2AE1 28F6 DF36 110A 0E9C A320 BBE8 2B52 EE19
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{sent by mu4e on Emacs running under GNU/Linux}
(Choose Linux, Choose Freedom)
