### ISSUE TITLE
Crash attempting to open external links on Android 12

### ISSUE THREAD

**Issue by hackel** [ccrama/Slide#3388]
Slide version: 6.7.1
Android version: 12 beta 2

Whenever I attempt to open an external link, Slide crashes.  Clicking on a link post simply does nothing, but if I manually choose "open externally," it crashes.  Clicking on any link in a comment causes a crash as well.

I captured the following stack trace:
```
06-18 20:58:56.761 30028 30028 E AndroidRuntime: FATAL EXCEPTION: main
06-18 20:58:56.761 30028 30028 E AndroidRuntime: Process: me.ccrama.redditslide, PID: 30028
06-18 20:58:56.761 30028 30028 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ActivityInfo android.content.pm.ResolveInfo.activityInfo' on a null object reference
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at me.ccrama.redditslide.util.LinkUtil.overridePackage(LinkUtil.java:234)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at me.ccrama.redditslide.util.LinkUtil.openExternally(LinkUtil.java:202)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at me.ccrama.redditslide.SubmissionViews.HeaderImageLinkView$2.onClick(HeaderImageLinkView.java:621)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at com.cocosw.bottomsheet.BottomSheet$4.onItemClick(BottomSheet.java:332)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3190)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4167)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7796)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-18 20:58:56.761 30028 30028 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
06-18 20:58:56.770  1771  1814 W ActivityTaskManager:   Force finishing activity me.ccrama.redditslide/.Activities.MainActivity
06-18 20:58:56.874  1771  3842 I ActivityManager: Process me.ccrama.redditslide (pid 30028) has died: fg  TOP 
```

This may be a dupe of #3387, but my experience is not limited to Twitter, it happens on all links, regardless of which external browser I choose.

Might have something to do with this nonsense.  https://developer.android.com/about/versions/12/web-intent-resolution

**Comment by hackel** [comment]
This appears to have resolved itself in Android 12 beta 4.
