### ISSUE TITLE
App crashed when loading image gallery.

### ISSUE THREAD

**Issue by yasmara** [ccrama/Slide#339]
I tapped to open an image gallery from a post in /r/movies and it showed a black screen for 5 seconds and the app crashed.

Debug info:
 OS Version: 3.10.40-g909db78(2256973)
 OS API Level: 23
 Device: flounder
 Model (and Product): Nexus 9 (volantis)
 RELEASE: 6.0
 BRAND: google
 DISPLAY: MRA58K
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: flounder
 MANUFACTURER: htc
 SLIDE VERSION: 73

Stacktrace: 

```
android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class <unknown>
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at me.ccrama.redditslide.Adapters.CommentAdapter.onBindViewHolder(CommentAdapter.java:586)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5212)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5245)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4483)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:386)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
	at android.view.View.layout(View.java:16630)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	... 66 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	... 71 more
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f01028f a=-1}
	at android.content.res.TypedArray.getDrawable(TypedArray.java:867)
	at android.view.View.<init>(View.java:3948)
	at android.view.ViewGroup.<init>(ViewGroup.java:573)
	at android.widget.LinearLayout.<init>(LinearLayout.java:203)
	at android.widget.LinearLayout.<init>(LinearLayout.java:199)
	at android.widget.LinearLayout.<init>(LinearLayout.java:195)
	... 73 more
```

**Comment by ccrama** [comment]
Are you sure you were opening a gallery? It crashed on comment code

**Comment by yasmara** [comment]
Sorry I was doing other things while I was reporting this and I must have muddled up which bug I was reporting. The bug this post actually refers to is a crash when pressing the 3 dot menu on a post to make a comment.

**Comment by l3d00m** [comment]
I think this is related to the landscape comment mode crashes and therefore fixed now.
