### ISSUE TITLE
Unsubscribe crash 

### ISSUE THREAD

**Issue by emacsomancer** [ccrama/Slide#340]
tried to unsubscribe from subreddit, keeps crashing 

Debug info:
 OS Version: 3.4.0-g6af28ec(448934.10)
 OS API Level: 21
 Device: htc_m8
 Model (and Product): HTC One M8 (htc_europe)
 RELEASE: 5.0.2
 BRAND: htc
 DISPLAY: LRX22G release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: HTC
 SLIDE VERSION: 73

Stacktrace: 

```android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:724)
	at okio.Okio$1.write(Okio.java:78)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:201)
	at com.squareup.okhttp.internal.spdy.Spdy3$Writer.synStream(Spdy3.java:339)
	at com.squareup.okhttp.internal.spdy.SpdyConnection.newStream(SpdyConnection.java:266)
	at com.squareup.okhttp.internal.spdy.SpdyConnection.newStream(SpdyConnection.java:242)
	at com.squareup.okhttp.internal.http.SpdyTransport.writeRequestHeaders(SpdyTransport.java:89)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:814)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
	at com.squareup.okhttp.Call.getResponse(Call.java:272)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
	at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.managers.AccountManager.setSubscribed(AccountManager.java:266)
	at net.dean.jraw.managers.AccountManager.subscribe(AccountManager.java:245)
	at me.ccrama.redditslide.Activities.SubredditOverview$13.onCheckedChanged(SubredditOverview.java:387)
	at android.widget.CompoundButton.setChecked(CompoundButton.java)
	at android.widget.CompoundButton.toggle(CompoundButton.java)
	at android.widget.CompoundButton.performClick(CompoundButton.java)
	at android.view.View$PerformClick.run(View.java)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by emacsomancer** [comment]
also crashing when I try to subscribe

**Comment by l3d00m** [comment]
merging this into #343
