### ISSUE TITLE
App crash on certain reddit post

### ISSUE THREAD

**Issue by HeyBanditoz** [ccrama/Slide#3414]
Slide version: v6.7.1
Android version: 10
Post is https://v.redd.it/at87ox5fdun71 or https://www.reddit.com/r/watchpeoplesurvive/comments/ppalp6/crossing_the_street/
Stack trace from logcat
```
FATAL EXCEPTION: AsyncTask #3
Process: me.ccrama.redditslide, PID: 25903
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: url == null
	at okhttp3.Request$Builder.url(Request.java:156)
	at me.ccrama.redditslide.util.GifUtils$AsyncLoadGif.getRemoteFileSize(GifUtils.java:956)
	at me.ccrama.redditslide.util.GifUtils$AsyncLoadGif.doInBackground(GifUtils.java:628)
	at me.ccrama.redditslide.util.GifUtils$AsyncLoadGif.doInBackground(GifUtils.java:336)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

**Comment by LeSnake04** [comment]
It doesn't crash for me.

**Comment by PurpleCodingWizard** [comment]
I confirm a crash on my end too. Here's another post who's video which crashes in a similar way: https://reddit.com/r/StartledCats/comments/pqvkvk/big_mistake_kitty/
