### ISSUE TITLE
crash when upvoting comment

### ISSUE THREAD

**Issue by emacsomancer** [ccrama/Slide#351]
In multicolumn mode, had a post open, and tried to upvote one of the comments and it crashed.(

Debug info:
 OS Version: 3.1.10-katkernel-021-nousergpu+(eng.timduru.20151013.090254)
 OS API Level: 22
 Device: tf300t
 Model (and Product): TF300T (full_tf300t)
 RELEASE: 5.1.1
 BRAND: Asus
 DISPLAY: LMY48W KatKiss-5.1.1_030
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: cardhu
 MANUFACTURER: unknown
 SLIDE VERSION: 73

Stacktrace: 

```
android.view.InflateException: Binary XML file line #12: Error inflating class ImageView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at me.ccrama.redditslide.Adapters.CommentAdapter.doHighlighted(CommentAdapter.java:252)
	at me.ccrama.redditslide.Adapters.CommentAdapter.doLongClick(CommentAdapter.java:526)
	at me.ccrama.redditslide.Adapters.CommentAdapter$9.onLongClick(CommentAdapter.java:669)
	at android.view.View.performLongClick(View.java:4819)
	at android.view.View$CheckForLongPress.run(View.java:19840)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5296)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 5
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
	at android.widget.ImageView.<init>(ImageView.java:173)
	at android.widget.ImageView.<init>(ImageView.java:135)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
	at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:98)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:926)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:980)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
	... 18 more
```

**Comment by Alexendoo** [comment]
#604
