### ISSUE TITLE
Slide wasn't even running...

### ISSUE THREAD

**Issue by alexsmithfanning** [ccrama/Slide#355]
Slide crashed after I haven't had it running, or even in memory.

Debug info:
 OS Version: 3.4.42-gd8f2775(45)
 OS API Level: 19
 Device: peregrine
 Model (and Product): XT1045 (peregrine_att)
 RELEASE: 4.4.4
 BRAND: motorola
 DISPLAY: KXB21.14-L1.63
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: motorola
 SLIDE VERSION: 73

Stacktrace: 

```java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='GET', url=https://oauth.reddit.com/api/multi/mine?expand_srs=true, expectedMediaType=application/json, headers=User-Agent: android:me.ccrama.RedditSlide:v4.0 (by /u/ccrama)
Authorization: bearer 44230988-HVpNQ8siUWft3ljdlH2e4GJ4Guw
, body=null}
	at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.managers.MultiRedditManager.mine(MultiRedditManager.java:42)
	at me.ccrama.redditslide.SubredditStorage.getMultireddits(SubredditStorage.java:357)
	at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:77)
	at me.ccrama.redditslide.SubredditStorage.doInBackground(SubredditStorage.java:28)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Caused by: java.net.UnknownHostException: Unable to resolve host "oauth.reddit.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
	at java.net.InetAddress.getAllByName(InetAddress.java:214)
	at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
	at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
	at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
	at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
	... 12 more
Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Posix.getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
	... 28 more
```

**Comment by yasmara** [comment]
When setting up my new Chromecast slide crashed a few times, even though it wasn't open

**Comment by l3d00m** [comment]
merge with #306
