### ISSUE TITLE
Crash on sidecar link

### ISSUE THREAD

**Issue by kelvinalfaro** [ccrama/Slide#363]
crash on link

Debug info:
 OS Version: 3.4.42-gb476356(4)
 OS API Level: 22
 Device: ghost
 Model (and Product): XT1053 (ghost_retail)
 RELEASE: 5.1
 BRAND: motorola
 DISPLAY: LPA23.12-15.5
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: motorola
 SLIDE VERSION: 73

Stacktrace: 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at me.ccrama.redditslide.Adapters.CommentAdapter.reset(CommentAdapter.java:144)
	at me.ccrama.redditslide.Fragments.CommentPage.doData(CommentPage.java:301)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.onPostExecute(SubmissionComments.java:85)
	at me.ccrama.redditslide.Adapters.SubmissionComments$LoadData.onPostExecute(SubmissionComments.java:71)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by ccrama** [comment]
Do you know which sidebar you clicked on? There isn't enough info here for me to fix it :(

**Comment by l3d00m** [comment]
isn't this fixed now?
