### ISSUE TITLE
Crashed while phone was standby

### ISSUE THREAD

**Issue by trentusus** [ccrama/Slide#365]
.

Debug info:
 OS Version: 3.4.0-g2b19159(454154.11)
 OS API Level: 21
 Device: htc_m8
 Model (and Product): HTC_0P6B6 (optus_au)
 RELEASE: 5.0.1
 BRAND: htc
 DISPLAY: LRX22C release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: HTC
 SLIDE VERSION: 73

Stacktrace: 

```java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='POST', url=https://www.reddit.com/api/v1/access_token, expectedMediaType=*/*, headers=User-Agent: android:me.ccrama.RedditSlide:v4.0 (by /u/ccrama)
Authorization: bearer 14260199-h128zngvbo1h3eNTo0f-5x9XI2k
, body=net.dean.jraw.http.RequestBody$DefaultRequestBody@bf13972}
	at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.http.oauth.OAuthHelper.refreshToken(OAuthHelper.java:307)
	at me.ccrama.redditslide.Authentication$UpdateToken.doInBackground(Authentication.java:68)
	at me.ccrama.redditslide.Authentication$UpdateToken.doInBackground(Authentication.java:53)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Caused by: java.net.ConnectException: failed to connect to www.reddit.com/198.41.208.141 (port 443): connect failed: ENETUNREACH (Network is unreachable)
	at libcore.io.IoBridge.connect(IoBridge.java:124)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
	at java.net.Socket.connect(Socket.java:882)
	at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:197)
	at com.squareup.okhttp.Connection.connect(Connection.java:156)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
	at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
	... 11 more
Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
	at libcore.io.Posix.connect(Native Method)
	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
	at libcore.io.IoBridge.connect(IoBridge.java:122)
	... 27 more
```

**Comment by l3d00m** [comment]
I'm getting this too.

**Comment by l3d00m** [comment]
This should be the same too: https://plus.google.com/+BikramAgarwal/posts/JJNFSGgLxA4

**Comment by l3d00m** [comment]
Another thing i just  noticied is that it only happens on a specific WIFI where all https connections are stripped (it says it has problems connecting to 443)

**Comment by ccrama** [comment]
Gracefully handled with d66b7ca
