### ISSUE TITLE
Slide crashed while restoring from backup

### ISSUE THREAD

**Issue by Snagg57** [ccrama/Slide#368]
Slide crash from restoring a previous backup.

Debug info:
 OS Version: 3.10.40-geec2459(1860966)
 OS API Level: 22
 Device: shamu
 Model (and Product): Nexus 6 (shamu)
 RELEASE: 5.1.1
 BRAND: google
 DISPLAY: LMY47Z
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: shamu
 MANUFACTURER: motorola
 SLIDE VERSION: 73

Stacktrace: 

```
java.lang.NullPointerException: Attempt to invoke interface method 'com.google.android.gms.common.api.PendingResult com.google.android.gms.drive.DriveFolder.listChildren(com.google.android.gms.common.api.GoogleApiClient)' on a null object reference
	at me.ccrama.redditslide.Activities.SettingsBackup$2.onClick(SettingsBackup.java:191)
	at android.view.View.performClick(View.java:4780)
	at android.view.View$PerformClick.run(View.java:19866)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by Alexendoo** [comment]
Backup/restore has changed a fair bit, most likely outdated by now
