### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by SolarAquarion** [ccrama/Slide#380]
I startup the app and it crashes

Debug info:
 OS Version: 3.4.0-Sultan-CAF(f25a48b24b)
 OS API Level: 22
 Device: A0001
 Model (and Product): A0001 (bacon)
 RELEASE: 5.1.1
 BRAND: oneplus
 DISPLAY: LMY48W release-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: bacon
 MANUFACTURER: OnePlus
 SLIDE VERSION: 73

Stacktrace: 

```
java.lang.IllegalArgumentException: LARGE is not a constant in me.ccrama.redditslide.SettingValues$InfoBar
	at java.lang.Enum.valueOf(Enum.java:200)
	at me.ccrama.redditslide.SettingValues$InfoBar.valueOf(SettingValues.java:36)
	at me.ccrama.redditslide.Views.PopulateSubmissionViewHolder.PopulateSubmissionViewHolder(PopulateSubmissionViewHolder.java:574)
	at me.ccrama.redditslide.Adapters.SubmissionAdapter.onBindViewHolder(SubmissionAdapter.java:262)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5212)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5245)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4483)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1034)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:744)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1180)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:757)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15686)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by l3d00m** [comment]
this is definitely not a duplicate, haven't seen it before
