### ISSUE TITLE
Crash out of nowhere (I finally got it :D)

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#388]
title

Debug info:
 OS Version: 3.10.61-5966591(N920TUVU2COJ5)
 OS API Level: 22
 Device: nobleltetmo
 Model (and Product): SM-N920T (nobleltetmo)
 RELEASE: 5.1.1
 BRAND: samsung
 DISPLAY: LMY47X.N920TUVU2COJ5
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: samsungexynos7420
 MANUFACTURER: samsung
 SLIDE VERSION: 73

Stacktrace: 

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Could not execute the request: HttpRequest {method='POST', url=https://www.reddit.com/api/v1/access_token, expectedMediaType=*/*, headers=User-Agent: android:me.ccrama.RedditSlide:v4.0 (by /u/ccrama)
Authorization: bearer ---Dont think this should be here---
, body=net.dean.jraw.http.RequestBody$DefaultRequestBody@e3622c6}
	at net.dean.jraw.http.RestClient.execute(RestClient.java:144)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
	at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
	at net.dean.jraw.http.oauth.OAuthHelper.refreshToken(OAuthHelper.java:307)
	at me.ccrama.redditslide.Authentication$UpdateToken.doInBackground(Authentication.java:80)
	at me.ccrama.redditslide.Authentication$UpdateToken.doInBackground(Authentication.java:60)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Caused by: java.net.UnknownHostException: Unable to resolve host "www.reddit.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
	at java.net.InetAddress.getAllByName(InetAddress.java:215)
	at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
	at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
	at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
	at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:64)
	at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
	... 11 more
```

**Comment by aprilhem** [comment]
@ccrama 

What is the fix to the problem? I stumbled upon this page from google search. It is the only page on the web with same problem that I am facing. what was the fix?

**Comment by Alexendoo** [comment]
The crash is (was) because of the unhandled UnknownHostException, DNS failed which is most likely due to a network issue, the solution would be to catch it and gracefully move on (for example pop up a failure message, retry later, etc)
