### ISSUE TITLE
Issues with (un)subscribing

### ISSUE THREAD

**Issue by l3d00m** [ccrama/Slide#399]
I'm using the newest code for this

1. Unsubcribing simply does not work (still showing as subscribed on official website)
2. Subscribing to a subreddit (that is existing!) crashes with the following log:

```

java.lang.RuntimeException: An error occured while executing doInBackground()
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:300)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:  Caused by: net.dean.jraw.http.NetworkException: Request returned non-successful status code: 404 Not Found
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at net.dean.jraw.http.RestClient.execute(RestClient.java:132)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at net.dean.jraw.RedditClient.execute(RedditClient.java:147)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at net.dean.jraw.RedditClient.execute(RedditClient.java:141)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at net.dean.jraw.managers.AccountManager.setSubscribed(AccountManager.java:266)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at net.dean.jraw.managers.AccountManager.unsubscribe(AccountManager.java:255)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at me.ccrama.redditslide.Activities.SubredditView$9$1.doInBackground(SubredditView.java:663)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at me.ccrama.redditslide.Activities.SubredditView$9$1.doInBackground(SubredditView.java:654)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
11-07 14:33:09.894 24413-24704/me.ccrama.redditslide E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818) 

```

**Comment by ccrama** [comment]
Fixed 2234d51
