### ISSUE TITLE
Gucci Mane Ice Cream Tattoo

### ISSUE THREAD

**Issue by Dalamo** [ccrama/Slide#402]
What did it now moight

Debug info:
 OS Version: 3.4.5(173)
 OS API Level: 17
 Device: bonsai10
 Model (and Product): HP Slate 10 HD (penzai_w_a)
 RELEASE: 4.2.2
 BRAND: hp
 DISPLAY: v1.00.19_20140708.173_user
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: pxa988
 MANUFACTURER: Hewlett-Packard
 SLIDE VERSION: 73

Stacktrace: 

```java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.SubredditOverview}: android.view.InflateException: Binary XML file line #43: Error inflating class ImageView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
	at android.app.ActivityThread.access$600(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #43: Error inflating class ImageView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:789)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:792)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:792)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:792)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:792)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:517)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
	at me.ccrama.redditslide.Activities.SubredditOverview.onCreate(SubredditOverview.java:225)
	at android.app.Activity.performCreate(Activity.java:5104)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
	... 11 more
Caused by: java.lang.NumberFormatException: Invalid int: "res/color/abc_primary_text_material_dark.xml"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parse(Integer.java:375)
	at java.lang.Integer.parseInt(Integer.java:366)
	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:123)
	at android.content.res.TypedArray.getInt(TypedArray.java:254)
	at android.widget.ImageView.<init>(ImageView.java:146)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
	at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:98)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:926)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:980)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:718)
	... 25 more
```

**Comment by Alexendoo** [comment]
Old version, no information

**Comment by okungnyo** [comment]
"Gucci Mane Ice Cream Tattoo"?

lol
