### ISSUE TITLE
Tried to load a gif on /r/all

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#424]
Tried to load a gif

Debug info:
 OS Version: 3.4.67-cyanogenmod-g06b8e73(689a04335e)
 OS API Level: 22
 Device: A0001
 Model (and Product): A0001 (bacon)
 RELEASE: 5.1.1
 BRAND: oneplus
 DISPLAY: bacon-userdebug 5.1.1 LMY48W 689a04335e test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: bacon
 MANUFACTURER: OnePlus

Stacktrace: 

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Can not pass null context in to retrieve ion instance
	at com.koushikdutta.ion.Ion.getInstance(Ion.java)
	at com.koushikdutta.ion.Ion.getDefault(Ion.java)
	at com.koushikdutta.ion.Ion.with(Ion.java)
	at me.ccrama.redditslide.Fragments.GifFull$AsyncGyfcat.doInBackground(GifFull.java:226)
	at me.ccrama.redditslide.Fragments.GifFull$AsyncGyfcat.doInBackground(GifFull.java:217)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by l3d00m** [comment]
Autoreport is still working?

**Comment by SlideAutoreport** [comment]
No, I removed autoreport. Make sure to click report on the crash dialog!

**Comment by l3d00m** [comment]
this has the same stacktrace as #469, so i will merge it
