### ISSUE TITLE
Tried to load a gif and it broke

### ISSUE THREAD

**Issue by SlideAutoreport** [ccrama/Slide#452]
Once again, tried to load a gif and it broke

Debug info:
 OS Version: 3.4.67-cyanogenmod-g06b8e73(689a04335e)
 OS API Level: 22
 Device: A0001
 Model (and Product): A0001 (bacon)
 RELEASE: 5.1.1
 BRAND: oneplus
 DISPLAY: bacon-userdebug 5.1.1 LMY48W 689a04335e test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: bacon
 MANUFACTURER: OnePlus

Stacktrace: 

```
java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:182)
	at me.ccrama.redditslide.Activities.GifView$AsyncImageLoader$1$3$3$1.onBufferingUpdate(GifView.java:259)
	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2573)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5375)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by l3d00m** [comment]
looks like xposed's fault.
