### ISSUE TITLE
On Multiple swipe in Shadowbox Mode, App crashes

### ISSUE THREAD

**Issue by Mrraffikki** [ccrama/Slide#469]
If I swipe about 15 times in secession (quickly, but sometimes less, like 5), the app will crash and need to be restarted.

I'm on Nexus 5x running 6.0, build MDB08I

**Comment by Mrraffikki** [comment]
If I can get to 24 "swipes", It will not go any further

I am on slide v4.3.1 Pro

**Comment by l3d00m** [comment]
Stacktrace
´´´
Process: me.ccrama.redditslide, PID: 28028
                                                                       java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                           at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                           at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: java.lang.NullPointerException: Can not pass null context in to retrieve ion instance
                                                                           at com.koushikdutta.ion.Ion.getInstance(Ion.java:111)
                                                                           at com.koushikdutta.ion.Ion.getDefault(Ion.java:100)
                                                                           at com.koushikdutta.ion.Ion.with(Ion.java:72)
                                                                           at me.ccrama.redditslide.Fragments.AlbumFull$AsyncImageLoaderAlbum.doInBackground(AlbumFull.java:195)
                                                                           at me.ccrama.redditslide.Fragments.AlbumFull$AsyncImageLoaderAlbum.doInBackground(AlbumFull.java:129)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
´´´

**Comment by ccrama** [comment]
Ion isn't used for images anymore, so I think that has been fixed for a while

**Comment by okungnyo** [comment]
What did you switch to?
