### ISSUE TITLE
Crash using fastscroll after changing comment sorting type

### ISSUE THREAD

**Issue by karlding** [ccrama/Slide#537]
When you're at the bottom of the page and change the sorting type, then subsequently attempt to navigate to the next parent comment (I think **fastscroll** was renamed "Navigate between parent comments"), you may sometimes cause a crash (sometimes the crash doesn't happen).

```
11-15 02:54:59.102 31763 31763 E AndroidRuntime: FATAL EXCEPTION: main

11-15 02:54:59.102 31763 31763 E AndroidRuntime: Process: me.ccrama.redditslide, PID: 31763

11-15 02:54:59.102 31763 31763 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 199, size is 199

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:308)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at me.ccrama.redditslide.Adapters.CommentAdapter.getHiddenCountUpTo(CommentAdapter.java:929)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at me.ccrama.redditslide.Adapters.CommentAdapter.getRealPosition(CommentAdapter.java:915)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at me.ccrama.redditslide.Fragments.CommentPage$4.onClick(CommentPage.java:206)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at android.view.View.performClick(View.java:5198)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21147)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

11-15 02:54:59.102 31763 31763 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ccrama** [comment]
I don't think this is an issue anymore
