### ISSUE TITLE
crash when scroll down while refreshing subreddit

### ISSUE THREAD

**Issue by c727** [ccrama/Slide#572]
title

**Comment by Alexendoo** [comment]
```
D/AndroidRuntime( 3505): Shutting down VM
E/AndroidRuntime( 3505): FATAL EXCEPTION: main
E/AndroidRuntime( 3505): Process: me.ccrama.redditslide, PID: 3505
E/AndroidRuntime( 3505): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1aa54127 position=2 id=-1, oldPos=-1, pLpos:-1 no parent}
E/AndroidRuntime( 3505):        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4247)
E/AndroidRuntime( 3505):        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4378)
E/AndroidRuntime( 3505):        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)
E/AndroidRuntime( 3505):        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
E/AndroidRuntime( 3505):        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
E/AndroidRuntime( 3505):        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
E/AndroidRuntime( 3505):        at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1161)
E/AndroidRuntime( 3505):        at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1018)
E/AndroidRuntime( 3505):        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1492)
E/AndroidRuntime( 3505):        at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2416)
E/AndroidRuntime( 3505):        at android.view.View.dispatchTouchEvent(View.java:8471)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime( 3505):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime( 3505):        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
E/AndroidRuntime( 3505):        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
E/AndroidRuntime( 3505):        at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
E/AndroidRuntime( 3505):        at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
E/AndroidRuntime( 3505):        at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
E/AndroidRuntime( 3505):        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
E/AndroidRuntime( 3505):        at android.view.View.dispatchPointerEvent(View.java:8666)
E/AndroidRuntime( 3505):        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
E/AndroidRuntime( 3505):        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
E/AndroidRuntime( 3505):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
E/AndroidRuntime( 3505):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
E/AndroidRuntime( 3505):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
E/AndroidRuntime( 3505):        at android.view.ViewRootImpl$AsyncInputStage.
```
