### ISSUE TITLE
Typing 'gif' into search for a subreddit and scrolling down

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#644]
I'm pretty sure this had been fixed at one point, ~~however I can't find it in the issue tracker~~. Type 'gif' into the search field in the drawer and scroll to the bottom.

```
E/AndroidRuntime(14200): FATAL EXCEPTION: main
E/AndroidRuntime(14200): Process: me.ccrama.redditslide, PID: 14200
E/AndroidRuntime(14200): java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
E/AndroidRuntime(14200):        at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:239)
E/AndroidRuntime(14200):        at me.ccrama.redditslide.Visuals.Pallete.getColor(Pallete.java:63)
E/AndroidRuntime(14200):        at me.ccrama.redditslide.Adapters.SideArrayAdapter.getView(SideArrayAdapter.java:60)
E/AndroidRuntime(14200):        at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
E/AndroidRuntime(14200):        at android.widget.AbsListView.obtainView(AbsListView.java:2347)
E/AndroidRuntime(14200):        at android.widget.ListView.makeAndAddView(ListView.java:1864)
E/AndroidRuntime(14200):        at android.widget.ListView.fillDown(ListView.java:698)
E/AndroidRuntime(14200):        at android.widget.ListView.fillGap(ListView.java:662)
E/AndroidRuntime(14200):        at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4991)
E/AndroidRuntime(14200):        at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3418)
E/AndroidRuntime(14200):        at android.widget.AbsListView.onTouchMove(AbsListView.java:3801)
E/AndroidRuntime(14200):        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3632)
E/AndroidRuntime(14200):        at android.view.View.dispatchTouchEvent(View.java:8471)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
E/AndroidRuntime(14200):        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
E/AndroidRuntime(14200):        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
E/AndroidRuntime(14200):        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
E/AndroidRuntime(14200):        at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
E/AndroidRuntime(14200):        at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
E/AndroidRuntime(14200):        at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
E/AndroidRuntime(14200):        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
E/AndroidRuntime(14200):        at android.view.View.dispatchPointerEvent(View.java:8666)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
E/AndroidRuntime(14200):        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
E/AndroidRuntime(14200):        at android.view.InputEventReceiver.dispatchInputEven
```

**Comment by Alexendoo** [comment]
It's the same as #187

**Comment by Deadleg** [comment]
Can't reproduce this from commit 3c096f7f9e3121fd5301167d148c854c21f6b4d6.

Is this still an issue?

**Comment by l3d00m** [comment]
I can't reproduce it too.

**Comment by Alexendoo** [comment]
No longer happening for me either on later commits, can't recall the version I was on but it was from an apk posted in IRC
