### ISSUE TITLE
Tapping Comments Crash

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#73]
## Info
Unhid a comment. 

## Stacktrace
```java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{27ab4c27 position=825 id=-1, oldPos=4, pLpos:4 scrap tmpDetached no parent}at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4349)at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4480)at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4461)at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1962)at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1371)at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1334)at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2801)at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3145)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)at android.widget.FrameLayout.onLayout(FrameLayout.java:514)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)at android.widget.FrameLayout.onLayout(FrameLayout.java:514)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)at android.widget.FrameLayout.onLayout(FrameLayout.java:514)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)at android.widget.FrameLayout.onLayout(FrameLayout.java:514)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)at android.widget.FrameLayout.onLayout(FrameLayout.java:514)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:386)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)at android.widget.FrameLayout.onLayout(FrameLayout.java:514)at android.view.View.layout(View.java:16942)at android.view.ViewGroup.layout(ViewGroup.java:5409)at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2457)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2160)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1300)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7017)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)at android.view.Choreographer.doCallbacks(Choreographer.java:590)at android.view.Choreographer.doFrame(Choreographer.java:560)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)at android.os.Handler.handleCallback(Handler.java:739)at android.os.Handler.dispatchMessage(Handler.java:95)at android.os.Looper.loop(Looper.java:145)at android.app.ActivityThread.main(ActivityThread.java:6891)at java.lang.reflect.Method.invoke(Native Method)at java.lang.reflect.Method.invoke(Method.java:372)at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)```

Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Fixed with a5f55db411cbcc0448d58519abe9bc6fd40908ac
