### ISSUE TITLE
Multitasking Back to Send Message

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#75]
## Stacktrace
```java.lang.RuntimeException: Unable to destroy activity {me.ccrama.redditslide/me.ccrama.redditslide.Activities.CommentsScreen}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4852)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4870)
at android.app.ActivityThread.access$1600(ActivityThread.java:197)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735)
at android.os.Handler.disp
atchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6891)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
at me.ccrama.redditslide.Fragments.CommentPage.onCre
ateView(CommentPage.java:179)
at android.support.v4.app.Fragment.performCre
ateView(Fragment.java:1962)
at android.support.v4.app.FragmentManagerImpl.moveToSt
ate(FragmentManager.java:1026)
at android.support.v4.app.FragmentManagerImpl.moveToSt
ate(FragmentManager.java:1207)
at android.support.v4.app.FragmentManagerImpl.moveToSt
ate(FragmentManager.java:1189)
at android.support.v4.app.FragmentManagerImpl.disp
atchReallyStop(FragmentManager.java:2028)
at android.support.v4.app.FragmentController.disp
atchReallyStop(FragmentController.java:213)
at android.support.v4.app.FragmentActivity.onReallyStop(FragmentActivity.java:713)
at android.support.v4.app.FragmentActivity.doReallyStop(FragmentActivity.java:699)
at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:288)
at android.support.v7.app.AppComp
atActivity.onDestroy(AppComp
atActivity.java:161)
at android.app.Activity.performDestroy(Activity.java:6784)
at android.app.Instrument
ation.callActivityOnDestroy(Instrument
ation.java:1155)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4830)... 10 more```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Cannot reproduce again
