### ISSUE TITLE
Issue saving Reddit preferences

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide#751]
Stacktrace:

```java
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: Could not find value for ["en","en-us"]
	at net.dean.jraw.AccountPreferencesEditor.val(AccountPreferencesEditor.java:52)
	at net.dean.jraw.AccountPreferencesEditor.<init>(AccountPreferencesEditor.java:35)
	at me.ccrama.redditslide.Activities.SettingsReddit$1.doInBackground(SettingsReddit.java:41)
	at me.ccrama.redditslide.Activities.SettingsReddit$1.doInBackground(SettingsReddit.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

Appears to be an issue with JRAW. Any idea of why this would be occuring @thatJavaNerd?

**Comment by thatJavaNerd** [comment]
In that account's [preferences](https://www.reddit.com/prefs), what is the interface language?

**Comment by ccrama** [comment]
@thatJavaNerd probably not english, but I never override the language when retrieving or saving the AccountPreferencesEditor, though.

**Comment by thatJavaNerd** [comment]
This specific error occurs when [`AccountPreferencesEditor.val()`](https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/AccountPreferencesEditor.java#L40-L53) tries to identify the type of object a given JsonNode is. It knows how to handle a null object, boolean, int, String, and an array of one element. The value for `lang` is an array of two elements so it doesn't know how to handle it and throws an error.

In v0.8.1 I'm going to either minify or do away with AccountPreferences(Editor) in favor of a plain key-value lookup.

**Comment by okungnyo** [comment]
So it can't be fixed until v0.8.1 is released?

**Comment by thatJavaNerd** [comment]
That is correct. I think there's almost enough unpublished content to justify a new release. It should be out within the next few days.

**Comment by okungnyo** [comment]
Then I hope that lines up well enough for it to be included in Slide v4.5 final. (It's in alpha now.)

**Comment by thatJavaNerd** [comment]
This issue is possibly related to #756

**Comment by ccrama** [comment]
Great to hear that @thatJavaNerd ! Thank you for your work on JRAW

**Comment by ccrama** [comment]
@thatJavaNerd  Just updated Slide to use JRAW v0.8 (current on Github) and it appears that the methods to set 18 and set NSFW thumbnails visible are gone from the AccountPreferencesEditor class. Are they moved somewhere or just not stable enough to use yet? Thank you!

Commit: 2da9084f836ed0211629258404e19e1f500c4440

**Comment by ccrama** [comment]
Not applicable anymore, moved Reddit settings to open with reddit.com/prefs now.

**Comment by l3d00m** [comment]
@ccrama I think you have to do that manually now instead of using the AccountPreferencesEditor, see this commit: https://github.com/thatJavaNerd/JRAW/commit/3a189cb3624319f7477916a9e243ceadff9461f8
