### ISSUE TITLE
Single mode enabled causes a crash on start

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#83]
## Info
Enable single mode, try and open the app
## Stacktrace
```java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.SubredditOverviewSingle}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.DrawerLayout.setDrawerLockMode(int, int)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.disp
atchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.DrawerLayout.setDrawerLockMode(int, int)' on a null object reference
at me.ccrama.redditslide.Activities.SubredditOverviewSingle.doSubSidebar(SubredditOverviewSingle.java:631)
at me.ccrama.redditslide.Activities.SubredditOverviewSingle.setD
ataSet(SubredditOverviewSingle.java:1152)
at me.ccrama.redditslide.Activities.SubredditOverviewSingle.onCre
ate(SubredditOverviewSingle.java:184)
at android.app.Activity.performCre
ate(Activity.java:5990)
at android.app.Instrument
ation.callActivityOnCre
ate(Instrument
ation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)... 10 more```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Fixed cd352a45ca6ecabffd2d1bb915bdfd3d2320200a
