### ISSUE TITLE
Crash when reordering subreddits

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#841]
Happens every time you back out of it, either when you reorder something and hit save, or when not reordering anything at all.

```
E/AndroidRuntime(27429): FATAL EXCEPTION: main
E/AndroidRuntime(27429): Process: me.ccrama.redditslide, PID: 27429
E/AndroidRuntime(27429): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3, result=0, data=null} to activity {me.ccrama.redditslide/me.ccrama.redditslide.Activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.TabLayout.setupWithViewPager(android.support.v4.view.ViewPager)' on a null object reference
E/AndroidRuntime(27429):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
E/AndroidRuntime(27429):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
E/AndroidRuntime(27429):        at android.app.ActivityThread.access$1300(ActivityThread.java:151)
E/AndroidRuntime(27429):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
E/AndroidRuntime(27429):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(27429):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(27429):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(27429):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27429):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(27429):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(27429):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(27429): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.TabLayout.setupWithViewPager(android.support.v4.view.ViewPager)' on a null object reference
E/AndroidRuntime(27429):        at me.ccrama.redditslide.Activities.MainActivity$30.run(MainActivity.java:1061)
E/AndroidRuntime(27429):        at android.app.Activity.runOnUiThread(Activity.java:5293)
E/AndroidRuntime(27429):        at me.ccrama.redditslide.Activities.MainActivity.resetAdapter(MainActivity.java:1053)
E/AndroidRuntime(27429):        at me.ccrama.redditslide.Activities.MainActivity.onActivityResult(MainActivity.java:134)
E/AndroidRuntime(27429):        at android.app.Activity.dispatchActivityResult(Activity.java:6192)
E/AndroidRuntime(27429):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
E/AndroidRuntime(27429):        ... 10 more
```

**Comment by ccrama** [comment]
Fixed
