### ISSUE TITLE
Clicked on a subreddit (r/androidthemes), app crashed.

### ISSUE THREAD

**Issue by Dalamo** [ccrama/Slide#89]
## Stacktrace
```java.lang.NullPointerException
at me.ccrama.redditslide.Activities.SubredditOverview.doSubSidebar(SubredditOverview.java:305)
at me.ccrama.redditslide.Activities.SubredditOverview$OverviewPagerAdapter$1.onPageSelected(SubredditOverview.java:1298)
at android.support.v4.view.ViewPager.disp
atchOnPageSelected(ViewPager.java:1788)
at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:569)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:553)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:1627)
at android.support.design.widget.TabLayout.selectTab(TabLayout.java:837)
at android.support.design.widget.TabLayout.selectTab(TabLayout.java:809)
at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1077)
at android.support.design.widget.TabLayout$1.onClick(TabLayout.java:643)
at android.view.View.performClick(View.java:4204)
at android.view.View$PerformClick.run(View.java:17363)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.disp
atchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeN
ative(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.N
ativeStart.main(N
ative Method)```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Looks like an xposed module issue. Try disabling xposed and see if that works!
