### ISSUE TITLE
opened image from the tattoo sub, imgur I believe. 

### ISSUE THREAD

**Issue by Dowenprs** [ccrama/Slide#90]
## Stacktrace
```java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsoluteP
ath()' on a null object reference
at me.ccrama.redditslide.Activities.FullscreenImage.saveImageLocally(FullscreenImage.java:287)
at me.ccrama.redditslide.Activities.FullscreenImage.access$000(FullscreenImage.java:38)
at me.ccrama.redditslide.Activities.FullscreenImage$5.onClick(FullscreenImage.java:152)
at android.view.View.performClick(View.java:5198)
at android.view.View$PerformClick.run(View.java:21147)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.disp
atchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(N
ative Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Fixed with 4a11cea2144a2e016eb28503aaa0cb31337ef935
