### ISSUE TITLE
Crash when swiping quickly through shadowbox

### ISSUE THREAD

**Issue by kufii** [ccrama/Slide#910]
If you don't let the images load in the shadowbox and just swipe through quickly, slide crashes

**Comment by ccrama** [comment]
I cant fix this without some log or crash file. Possibly an OOM, though

**Comment by l3d00m** [comment]
Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonObject.toString()' on a null object reference
                                                                         at me.ccrama.redditslide.Fragments.AlbumFull$AsyncImageLoaderAlbum$1.onCompleted(AlbumFull.java:149)
                                                                         at me.ccrama.redditslide.Fragments.AlbumFull$AsyncImageLoaderAlbum$1.onCompleted(AlbumFull.java:146)
                                                                         at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
                                                                         at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
                                                                         at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:124)
                                                                         at com.koushikdutta.ion.IonRequestBuilder$1.run(IonRequestBuilder.java:244)
                                                                         at com.koushikdutta.async.AsyncServer$RunnableWrapper.run(AsyncServer.java:57)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5349)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by ccrama** [comment]
That has been fixed with the new AlbumUtils implementation
