### ISSUE TITLE
Crashwhileloadingcomments.jpg

### ISSUE THREAD

**Issue by Dalamo** [ccrama/Slide#93]
## Stacktrace
```java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.n
ativeDecodeAsset(N
ative Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:502)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:355)
at android.graphics.drawable.Drawable.cre
ateFromResourceStream(Drawable.java:785)
at android.content.res.Resources.loadDrawable(Resources.java:1965)
at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
at android.widget.ImageView.<init>(ImageView.java:120)
at android.support.v7.widget.AppComp
atImageView.<init>(AppComp
atImageView.java:60)
at android.support.v7.widget.AppComp
atImageView.<init>(AppComp
atImageView.java:56)
at android.support.v7.internal.app.AppComp
atViewInfl
ater.cre
ateView(AppComp
atViewInfl
ater.java:98)
at android.support.v7.app.AppComp
atDeleg
ateImplV7.cre
ateView(AppComp
atDeleg
ateImplV7.java:926)
at android.support.v7.app.AppComp
atDeleg
ateImplV7.onCre
ateView(AppComp
atDeleg
ateImplV7.java:980)
at android.support.v4.view.LayoutInfl
aterComp
atHC$FactoryWrapperHC.onCre
ateView(LayoutInfl
aterComp
atHC.java:44)
at android.view.LayoutInfl
ater.cre
ateViewFromTag(LayoutInfl
ater.java:718)
at android.view.LayoutInfl
ater.rInfl
ate(LayoutInfl
ater.java:789)
at android.view.LayoutInfl
ater.infl
ate(LayoutInfl
ater.java:517)
at android.view.LayoutInfl
ater.infl
ate(LayoutInfl
ater.java:424)
at android.view.LayoutInfl
ater.infl
ate(LayoutInfl
ater.java:380)
at android.support.v7.app.AppComp
atDeleg
ateImplV7.setContentView(AppComp
atDeleg
ateImplV7.java:257)
at android.support.v7.app.AppComp
atActivity.setContentView(AppComp
atActivity.java:109)
at me.ccrama.redditslide.Activities.Crash.onCre
ate(Crash.java:31)
at android.app.Activity.performCre
ate(Activity.java:5104)
at android.app.Instrument
ation.callActivityOnCre
ate(Instrument
ation.java:1080)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
at android.app.ActivityThread.access$600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
at android.os.Handler.disp
atchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeN
ative(N
ative Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.N
ativeStart.main(N
ative Method)```
Reported via Slide Crash Capture

**Comment by ccrama** [comment]
Same as your other issue,  Jellybean is somewhat supported but there are going to be issues. Nothing I can really fix, unfortunately.
