### ISSUE TITLE
Crashes after inactivity 

### ISSUE THREAD

**Issue by LordManhattan** [ccrama/Slide#935]
App crashes after long-ish periods of inactivity. If I use the app, leave it in the background and come back to it a couple of hours later, it will crash 100% of the time. 

> 01-30 15:49:24.582 E/AndroidRuntime(12410): java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.CommentsScreen}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
> 
> 01-30 15:49:24.582 E/AndroidRuntime(12410): 	at me.ccrama.redditslide.Activities.CommentsScreen.onCreate(CommentsScreen.java:68)

**Comment by l3d00m** [comment]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.CommentsScreen}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at java.util.ArrayList.addAll(ArrayList.java:188)
	at me.ccrama.redditslide.Activities.CommentsScreen.onCreate(CommentsScreen.java:68)
	at android.app.Activity.performCreate(Activity.java:6020)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284)
	... 10 more
    ```

**Comment by ccrama** [comment]
What did you do to reproduce @l3d00m ?

**Comment by l3d00m** [comment]
Not completely sure @ccrama, I just get that crash from time to time, but I can't do it intentionally :(

**Comment by LordManhattan** [comment]
It always happens to me when I leave the app open for several hours, so you would probably be able to reproduce the crash if you just open the app, hit the home-button and use your device as normal. Then, a couple of hours from now, open it, and it should crash when you switch back to it. It's the only app I have installed with this behavior, so it's kinda weird.

**Comment by l3d00m** [comment]
The crash just happened for me again after I clicked a link in a self post (using an external browser) and got back to it after a longer time.

**Comment by ccrama** [comment]
This shouldn't be an issue in v4.6 anymore
